Repository gofractally/psibase, pull requests merged in 2023-11, with the labels that each got.

#506 Fix simpleUI
  rust/psibase/src/boot.rs
Labels: bug, System app

#512 Fix third-party C++ service development
  libraries/psibase/CMakeLists.txt
Labels: bug, Dev Experience

#513 Reduce log severity when psinode can't lock db memory
  programs/psinode/main.cpp
Labels: Dev Experience, Node infra

#514 Fix bug in test case
  libraries/net/test/test_bft_consensus.cpp
Labels: bug

#515 Minor tweaks to options
  programs/psinode/main.cpp
Labels: Node infra

#524 Fix doc sys app
  .vscode/settings.json.sample
  doc/psidk/book.toml.in
  rust/gen-cpp-doc/src/main.rs
  rust/psibase/src/boot.rs
Labels: documentation, Dev Experience
