Repository gofractally/psibase, pull requests merged in 2024-02, with the labels that each got.

#559 Clean up old/unused UI items
  .vscode/tasks.json.sample
  CMakeLists.txt
  generator/package.json
  generator/tools/generate.js
  generator/tools/templates/contract/CMakeLists.txt
  generator/tools/templates/contract/deploy.sh
  generator/tools/templates/contract/include/services/user/__contract__.hpp
  generator/tools/templates/contract/src/__contract__.cpp
  generator/tools/templates/contract/test/CMakeLists.txt
  generator/tools/templates/contract/test/src/__contract__-test.cpp
  generator/tools/templates/react/.eslintignore
  generator/tools/templates/react/.eslintrc.js
  generator/tools/templates/react/.gitignore
  generator/tools/templates/react/.prettierrc.json
  generator/tools/templates/react/README.md
  generator/tools/templates/react/index.html
  generator/tools/templates/react/package.json
  generator/tools/templates/react/postcss.config.cjs
  generator/tools/templates/react/public/vite.svg
  generator/tools/templates/react/src/App.css
  generator/tools/templates/react/src/App.tsx
  generator/tools/templates/react/src/helpers.ts
  generator/tools/templates/react/src/main.tsx
  generator/tools/templates/react/src/styles/globals.css
  generator/tools/templates/react/src/vite-env.d.ts
  generator/tools/templates/react/tailwind.config.cjs
  generator/tools/templates/react/tsconfig.json
  generator/tools/templates/react/tsconfig.node.json
  generator/tools/templates/react/vite.config.ts
  generator/tools/templates/react/yarn.lock
  generator/yarn.lock
  services/system/AccountSys/ui/vanilla/index.html
  services/system/AccountSys/ui/vanilla/index.js
  services/user/CommonSys/common-lib/src/rpc.ts
  services/user/CommonSys/common/rpc.mjs
  services/user/CommonSys/ui/vanilla/common.index.html
  services/user/CommonSys/ui/vanilla/index.html
  services/user/CommonSys/ui/vanilla/index.js
  services/user/TokenSys/ui/vanilla/index.js
Labels: Refactoring

#569 Remove cmake variables for partial builds
  .vscode/tasks.json.sample
  CMakeLists.txt
  README.md
  external/CMakeLists.txt
  native/CMakeLists.txt
Labels: Dev Experience

#570 Extend boot transaction expiration to 120s (from 30s)
  rust/psibase/src/boot.rs
Labels: Dev Experience

#543 Update CI/CD builder image
  .github/workflows/ubuntu-builder.yml
Labels: no-log

#606 update builder with version that includes wasm32-unknown-unknown
  .github/workflows/ubuntu-builder.yml
Labels: no-log

#618 regenerate common-sys lockfile
  services/user/CommonSys/ui/yarn.lock
Labels: no-log

#620 Fix incorrect use of shared_lock
  programs/psinode/main.cpp
Labels: bug

#619 Some refactoring of http.cpp
  libraries/psibase_http/http.cpp
Labels: Refactoring
