Repository gofractally/psibase, pull requests merged in 2024-11, with the labels that each got.

#831 Registry app - Phase 1
  services/user/Registry/Cargo.lock
  services/user/Registry/Cargo.toml
  services/user/Registry/README.md
  services/user/Registry/plugin/Cargo.lock
  services/user/Registry/plugin/Cargo.toml
  services/user/Registry/plugin/src/errors.rs
  services/user/Registry/plugin/src/lib.rs
  services/user/Registry/plugin/src/queries.rs
  services/user/Registry/plugin/src/types.rs
  services/user/Registry/plugin/wit/impl.wit
  services/user/Registry/plugin/wit/world.wit
  services/user/Registry/query/Cargo.lock
  services/user/Registry/query/Cargo.toml
  services/user/Registry/query/src/lib.rs
  services/user/Registry/service/Cargo.lock
  services/user/Registry/service/Cargo.toml
  services/user/Registry/service/src/lib.rs
  services/user/Registry/service/src/utils.rs
  services/user/Registry/src/lib.rs
Labels: System app

#856 Chainmail: implement save/unsave message #855
  services/system/AuthDelegate/plugin/Cargo.lock
  services/user/Chainmail/Cargo.lock
  services/user/Chainmail/plugin/Cargo.toml
  services/user/Chainmail/plugin/src/errors.rs
  services/user/Chainmail/plugin/src/lib.rs
  services/user/Chainmail/plugin/src/queries.rs
  services/user/Chainmail/plugin/src/serde_structs.rs
  services/user/Chainmail/plugin/wit/impl.wit
  services/user/Chainmail/plugin/wit/world.wit
  services/user/Chainmail/service/src/event_query_helpers.rs
  services/user/Chainmail/service/src/expanded_table.rs
  services/user/Chainmail/service/src/helpers.rs
  services/user/Chainmail/service/src/lib.rs
  services/user/Chainmail/service/src/tables.rs
  services/user/Chainmail/ui/src/components/editor/control-bar.tsx
  services/user/Chainmail/ui/src/components/mail-display.tsx
  services/user/Chainmail/ui/src/components/mail-list.tsx
  services/user/Chainmail/ui/src/components/nav-menu.tsx
  services/user/Chainmail/ui/src/hooks/use-local-storage.ts
  services/user/Chainmail/ui/src/hooks/use-mail.ts
  services/user/Chainmail/ui/src/main.tsx
  services/user/Chainmail/ui/src/routes/index.ts
  services/user/Chainmail/ui/src/routes/saved.tsx
  services/user/Chainmail/ui/src/types.ts
  services/user/ClientData/plugin/Cargo.lock
  services/user/Invite/plugin_AuthInvite/Cargo.lock
Labels: System app

#904 Accounts plugin support connection tokens
  CMakeLists.txt
  dev/DemoApp1/plugin/Cargo.lock
  dev/DemoApp1/plugin/Cargo.toml
  dev/DemoApp1/service/Cargo.lock
  dev/DemoApp1/ui/src/App.tsx
  services/Cargo.lock
  services/Cargo.toml
  services/system/Accounts/plugin/Cargo.toml
  services/system/Accounts/plugin/account_tokens/.gitignore
  services/system/Accounts/plugin/account_tokens/Cargo.toml
  services/system/Accounts/plugin/account_tokens/src/lib.rs
  services/system/Accounts/plugin/account_tokens/wit/impl.wit
  services/system/Accounts/plugin/account_tokens/wit/world.wit
  services/system/Accounts/plugin/accounts/.gitignore
  services/system/Accounts/plugin/accounts/Cargo.toml
  services/system/Accounts/plugin/accounts/src/db/apps_table.rs
  services/system/Accounts/plugin/accounts/src/db/keys.rs
  services/system/Accounts/plugin/accounts/src/db/mod.rs
  services/system/Accounts/plugin/accounts/src/db/user_table.rs
  services/system/Accounts/plugin/accounts/src/errors.rs
  services/system/Accounts/plugin/accounts/src/helpers.rs
  services/system/Accounts/plugin/accounts/src/interfaces/active_app.rs
  services/system/Accounts/plugin/accounts/src/interfaces/admin.rs
  services/system/Accounts/plugin/accounts/src/interfaces/api.rs
  services/system/Accounts/plugin/accounts/src/interfaces/mod.rs
  services/system/Accounts/plugin/accounts/src/lib.rs
  services/system/Accounts/plugin/accounts/src/plugin.rs
  services/system/Accounts/plugin/accounts/src/tokens.rs
  services/system/Accounts/plugin/accounts/wit/impl.wit
  services/system/Accounts/plugin/accounts/wit/world.wit
  services/system/Accounts/plugin/src/lib.rs
  services/system/Accounts/plugin/wit/impl.wit
  services/system/Accounts/plugin/wit/world.wit
  services/system/AuthSig/plugin/Cargo.toml
  services/system/Transact/plugin/Cargo.toml
  services/system/Transact/plugin/src/helpers.rs
  services/user/Branding/ui/src/App.tsx
  services/user/Chainmail/plugin/Cargo.toml
  services/user/Chainmail/plugin/src/lib.rs
  services/user/Chainmail/ui/src/hooks/use-user.ts
  services/user/CommonApi/common/packages/wit/host-privileged.wit
  services/user/Identity/plugin/Cargo.toml
  services/user/Identity/plugin/src/lib.rs
  services/user/Invite/plugin/Cargo.toml
  services/user/Invite/plugin/src/lib.rs
  services/user/Invite/plugin/src/types.rs
  services/user/Invite/plugin/wit/impl.wit
  services/user/Invite/plugin/wit/world.wit
  services/user/Supervisor/ui/src/component-loading/privileged-api.js
  services/user/Supervisor/ui/src/plugin/pluginHost.ts
  services/user/Supervisor/ui/src/supervisor.ts
Labels: System app

#918 update ci/cd builder image
  .github/workflows/ubuntu-builder.yml
Labels: no-log

#917 Remove deprecated event-related code
  doc/psidk/src/development/services/cpp-service/reference/web-services.md
  libraries/psibase/common/include/psibase/eventIndex.hpp
  libraries/psibase/common/include/psibase/psibase.hpp
  libraries/psibase/common/include/psibase/serveGraphQL.hpp
  services/user/Fractal/include/services/user/CoreFractal.hpp
  services/user/Fractal/include/services/user/Fractal.hpp
  services/user/Fractal/include/services/user/fractalTables.hpp
  services/user/Fractal/src/Fractal.cpp
  services/user/Symbol/include/services/user/Symbol.hpp
  services/user/Symbol/include/services/user/symbolTables.hpp
  services/user/Symbol/src/Symbol.cpp
Labels: no-log

#925 Fix GraphQL schema generation
  libraries/psio/include/psio/graphql.hpp
Labels: bug, Dev Experience

#924 Add auth-sig key import
  services/system/AuthSig/include/services/system/AuthSig.hpp
  services/system/AuthSig/plugin/src/lib.rs
  services/system/AuthSig/plugin/wit/world.wit
  services/system/AuthSig/src/RAuthSig.cpp
Labels: System app

#927 Generalize argument merging for GraphQL
  libraries/psibase/common/include/psibase/serveGraphQL.hpp
  libraries/psibase/tester/include/psibase/tester.hpp
  libraries/psio/include/psio/graphql.hpp
  services/user/Tokens/src/RTokens.cpp
  services/user/Tokens/test/src/Tokens-test.cpp
Labels: Dev Experience

#932 Compressed snapshots
  doc/psidk/src/run-infrastructure/cli/psibase-create-snapshot.md
  programs/psinode/tests/test_snapshot.py
  programs/snapshot/CMakeLists.txt
  programs/snapshot/create-snapshot.cpp
  programs/snapshot/load-snapshot.cpp
  wasm/boost/CMakeLists.txt
Labels: Node infra
