Repository gofractally/psibase, pull requests merged in 2024-09, with the labels that each got.

#834 Fix error message
  rust/cargo-psibase/src/package.rs
Labels: no-log

#837 add some concepts to blob compare
  libraries/psibase/common/include/psibase/blob.hpp
Labels: no-log

#836 Fix warnings
  libraries/net/include/psibase/blocknet.hpp
  services/user/Nft/src/Nft.cpp
Labels: no-log

#819 Rebranding App
  rust/psibase/src/table.rs
  services/user/Branding/Cargo.lock
  services/user/Branding/Cargo.toml
  services/user/Branding/plugin/Cargo.lock
  services/user/Branding/plugin/Cargo.toml
  services/user/Branding/plugin/src/errors.rs
  services/user/Branding/plugin/src/lib.rs
  services/user/Branding/plugin/wit/world.wit
  services/user/Branding/service/Cargo.lock
  services/user/Branding/service/Cargo.toml
  services/user/Branding/service/src/lib.rs
  services/user/Branding/src/lib.rs
  services/user/Branding/ui/.eslintignore
  services/user/Branding/ui/.eslintrc.cjs
  services/user/Branding/ui/.gitignore
  services/user/Branding/ui/README.md
  services/user/Branding/ui/components.json
  services/user/Branding/ui/index.html
  services/user/Branding/ui/package.json
  services/user/Branding/ui/postcss.config.cjs
  services/user/Branding/ui/prettier.config.cjs
  services/user/Branding/ui/public/network_logo.svg
  services/user/Branding/ui/src/App.tsx
  services/user/Branding/ui/src/components/dropdown-menu.tsx
  services/user/Branding/ui/src/components/index.ts
  services/user/Branding/ui/src/components/nav.tsx
  services/user/Branding/ui/src/components/settings-dropdown.tsx
  services/user/Branding/ui/src/components/theme-provider.tsx
  services/user/Branding/ui/src/components/ui/button.tsx
  services/user/Branding/ui/src/components/ui/dropdown-menu.tsx
  services/user/Branding/ui/src/components/ui/hover-border-gradient.tsx
  services/user/Branding/ui/src/lib/utils.ts
  services/user/Branding/ui/src/main.tsx
  services/user/Branding/ui/src/shad/components/ui/button.tsx
  services/user/Branding/ui/src/shad/components/ui/dropdown-menu.tsx
  services/user/Branding/ui/src/shad/components/ui/input.tsx
  services/user/Branding/ui/src/shad/components/ui/label.tsx
  services/user/Branding/ui/src/shad/components/ui/separator.tsx
  services/user/Branding/ui/src/shad/components/ui/tabs.tsx
  services/user/Branding/ui/src/shad/components/ui/tooltip.tsx
  services/user/Branding/ui/src/styles/globals.css
  services/user/Branding/ui/src/vite-env.d.ts
  services/user/Branding/ui/tailwind.config.cjs
  services/user/Branding/ui/tsconfig.json
  services/user/Branding/ui/tsconfig.node.json
  services/user/Branding/ui/vite.config.ts
  services/user/Branding/ui/yarn.lock
Labels: System app

#850 Avoid throwing exceptions when parsing DWARF
  libraries/debug_eos_vm/dwarf.cpp
Labels: no-log

#852 Cleanup to native databases
  libraries/psibase/common/include/psibase/db.hpp
  libraries/psibase/common/include/psibase/nativeTables.hpp
  libraries/psibase/native/src/NativeFunctions.cpp
  rust/psibase/src/boot.rs
  rust/psibase/src/db.rs
  rust/psibase/src/native_tables.rs
  rust/psibase/src/services/producers.rs
  services/psibase_tests/event-service.cpp
  services/psibase_tests/event-service.hpp
  services/psibase_tests/test_event.cpp
Labels: Refactoring

#843 Update to wasi-sdk-24.0.
  CMakeLists.txt
Labels: Dev Experience

#857 Delete unused cicd script
  .github/workflows/on-pr-closed.yml
Labels: no-log

#860 do not comment out valid config item: database-cache-size
  programs/psinode/main.cpp
Labels: bug, Node infra

#865 Avoid throwing in WASM builds even when exceptions are "enabled"
  libraries/psio/include/psio/check.hpp
  libraries/psio/include/psio/view.hpp
Labels: Dev Experience

#859 Default deploy chainmail
  CMakeLists.txt
  doc/psidk/src/development/services/rust-service/package.md
  libraries/psibase/sdk/pack_service.cmake
  rust/cargo-psibase/src/package.rs
  rust/psibase/src/services/events.rs
  rust/test_package/Cargo.toml
  services/user/Chainmail/Cargo.lock
  services/user/Chainmail/Cargo.toml
  services/user/Chainmail/plugin/Cargo.toml
  services/user/Chainmail/service/Cargo.toml
  services/user/Chainmail/service/src/lib.rs
Labels: System app

#861 Union cargo package dependencies
  doc/psidk/src/development/services/rust-service/package.md
  rust/cargo-psibase/src/package.rs
  rust/psibase/src/package.rs
  services/user/Chainmail/Cargo.lock
  services/user/Chainmail/Cargo.toml
  services/user/Chainmail/plugin/Cargo.toml
  services/user/Chainmail/service/Cargo.toml
Labels: Dev Experience
