Repository gofractally/psibase, pull requests merged in 2024-10, with the labels that each got.

#872 bump version to 0.13.0
  CMakeLists.txt
  doc/psidk/src/development/services/rust-service/package.md
  libraries/psibase/common/include/psibase/version.hpp
  rust/Cargo.lock
  rust/Cargo.toml
  rust/burst-transfer/Cargo.toml
  rust/cargo-psibase/Cargo.toml
  rust/fracpack/Cargo.toml
  rust/psibase/Cargo.toml
  rust/psibase_macros/Cargo.toml
  rust/test_contract/Cargo.toml
  rust/test_contract_2/Cargo.toml
  rust/test_fracpack/Cargo.toml
  rust/test_package/Cargo.toml
  rust/test_package/plugin/Cargo.toml
  rust/test_package/query/Cargo.toml
  rust/test_package/service/Cargo.toml
  rust/test_service_elections/Cargo.toml
  rust/test_service_sites/Cargo.toml
  rust/test_subjective/Cargo.toml
  services/system/Accounts/plugin/Cargo.lock
  services/system/AuthSig/plugin/Cargo.lock
  services/system/Transact/plugin/Cargo.lock
  services/user/Branding/Cargo.toml
  services/user/Chainmail/Cargo.lock
  services/user/Chainmail/Cargo.toml
  services/user/Chainmail/plugin/Cargo.toml
  services/user/Chainmail/service/Cargo.toml
  services/user/Invite/plugin/Cargo.lock
  services/user/Sites/plugin/Cargo.lock
  services/user/Sites/plugin/Cargo.toml
  services/user/Tokens/plugin/Cargo.lock
  services/user/XAdmin/ui/yarn.lock
Labels: no-log

#864 Fix doc build for wasi-24
  rust/gen-cpp-doc/src/main.rs
Labels: no-log

#873 use v4 download
  .github/workflows/on-tag.yml
Labels: no-log

#882 Update docker images
  .github/workflows/ubuntu-builder.yml
Labels: no-log

#876 improve rust psibase package docs
  doc/psidk/src/development/services/rust-service/package.md
  doc/psidk/src/development/services/rust-service/testing.md
Labels: documentation, Dev Experience

#884 Supervisor: Handle multiple requests simultaneously
  services/user/Chainmail/service/src/lib.rs
  services/user/Chainmail/ui/src/components/mail-display.tsx
  services/user/Chainmail/ui/src/lib/utils.ts
  services/user/CommonApi/common/packages/common-lib/src/messaging/FunctionCallRequest.ts
  services/user/CommonApi/common/packages/common-lib/src/messaging/FunctionCallResponse.ts
  services/user/CommonApi/common/packages/common-lib/src/supervisor.ts
  services/user/Supervisor/ui/src/appInterace.ts
  services/user/Supervisor/ui/src/main.ts
  services/user/Supervisor/ui/src/supervisor.ts
Labels: Dev Experience

#887 Add trace to logging for failed transactions
  libraries/psibase/native/src/BlockContext.cpp
Labels: Node infra

#889 Fix onTransaction for sig/firstAuth failure
  libraries/psibase/native/include/psibase/BlockContext.hpp
  libraries/psibase/native/include/psibase/ForkDb.hpp
  libraries/psibase/native/src/BlockContext.cpp
  programs/psinode/main.cpp
  programs/psitest/main.cpp
Labels: bug, Node infra

#868 Add plugin data persistence doc
  doc/psidk/src/default-apps/README.md
  doc/psidk/src/specifications/app-architecture/plugins.md
Labels: documentation, Dev Experience
