Repository gofractally/psibase, pull requests merged in 2024-12, with the labels that each got.

#931 Handle percent encoded URLs
  libraries/psibase/CMakeLists.txt
  libraries/psibase/common/include/psibase/Rpc.hpp
  libraries/psibase/common/src/Rpc.cpp
  rust/Cargo.lock
  rust/psibase/Cargo.toml
  rust/psibase/src/http.rs
  services/Cargo.lock
  services/user/Branding/Cargo.lock
  services/user/Brotli/Cargo.lock
  services/user/Chainmail/Cargo.lock
  services/user/Chainmail/service/src/event_query_helpers.rs
  services/user/Packages/src/RPackages.cpp
  services/user/Registry/Cargo.lock
  services/user/Sites/src/Sites.cpp
Labels: Dev Experience

#935 Minor misc updates
  services/system/Accounts/plugin/accounts/wit/world.wit
  services/user/Tokens/src/RTokens.cpp
Labels: no-log

#941 remove ubuntu-2004 from on-tag workflow
  .github/workflows/on-tag.yml
Labels: no-log

#945 update publish script
  rust/scripts/publish.sh
Labels: no-log

#947 expect new TimePointSec serialization in invite plugin
  services/user/Invite/plugin/src/lib.rs
  services/user/Invite/plugin/src/types.rs
Labels: no-log

#946 clean up callstack-related browser console output
  services/user/Supervisor/ui/src/callStack.ts
Labels: no-log

#936 Delete old rust tests
  rust/CMakeLists.txt
  rust/Cargo.lock
  rust/Cargo.toml
  rust/test_service_elections/Cargo.toml
  rust/test_service_elections/README.md
  rust/test_service_elections/src/lib.rs
  rust/test_service_sites/Cargo.toml
  rust/test_service_sites/README.md
  rust/test_service_sites/src/lib.rs
Labels: no-log

#938 Improve boot related cli output
  libraries/psibase/native/include/psibase/ForkDb.hpp
  libraries/psibase_http/handle_request.cpp
  programs/psinode/main.cpp
  programs/psitest/main.cpp
  rust/psibase/src/main.rs
Labels: Dev Experience

#949 Auth sig support staged tx
  libraries/psibase/tester/src/DefaultTestChain.cpp
  services/system/AuthSig/CMakeLists.txt
  services/system/AuthSig/include/services/system/AuthSig.hpp
  services/system/AuthSig/src/AuthSig.cpp
  services/system/AuthSig/test/CMakeLists.txt
  services/system/AuthSig/test/src/AuthSig-test.cpp
  services/system/CMakeLists.txt
  services/system/StagedTx/service/cpp/include/services/system/StagedTx.hpp
  services/system/StagedTx/service/src/lib.rs
Labels: System app

#950 Restore boot log message
  programs/psinode/main.cpp
Labels: no-log

#940 Add accounts UI + Login on dashboard
  CMakeLists.txt
  services/system/Accounts/ui/README.md
  services/system/Accounts/ui/components.json
  services/system/Accounts/ui/eslint.config.js
  services/system/Accounts/ui/index.html
  services/system/Accounts/ui/package.json
  services/system/Accounts/ui/postcss.config.js
  services/system/Accounts/ui/public/vite.svg
  services/system/Accounts/ui/src/App.css
  services/system/Accounts/ui/src/App.tsx
  services/system/Accounts/ui/src/components/AccountSelection.tsx
  services/system/Accounts/ui/src/components/nav.tsx
  services/system/Accounts/ui/src/components/theme-provider.tsx
  services/system/Accounts/ui/src/components/ui/avatar.tsx
  services/system/Accounts/ui/src/components/ui/button.tsx
  services/system/Accounts/ui/src/components/ui/card.tsx
  services/system/Accounts/ui/src/components/ui/dialog.tsx
  services/system/Accounts/ui/src/components/ui/form.tsx
  services/system/Accounts/ui/src/components/ui/hover-border-gradient.tsx
  services/system/Accounts/ui/src/components/ui/input.tsx
  services/system/Accounts/ui/src/components/ui/label.tsx
  services/system/Accounts/ui/src/components/ui/skeleton.tsx
  services/system/Accounts/ui/src/hooks/useAcceptInvite.ts
  services/system/Accounts/ui/src/hooks/useDecode.ts
  services/system/Accounts/ui/src/hooks/useDecodeConnectionToken.ts
  services/system/Accounts/ui/src/hooks/useDecodeInviteToken.ts
  services/system/Accounts/ui/src/hooks/useDecodeToken.ts
  services/system/Accounts/ui/src/hooks/useGetAllAccounts.ts
  services/system/Accounts/ui/src/hooks/useLoginDirect.ts
  services/system/Accounts/ui/src/index.css
  services/system/Accounts/ui/src/lib/modifyUrlParams.ts
  services/system/Accounts/ui/src/lib/utils.ts
  services/system/Accounts/ui/src/main.tsx
  services/system/Accounts/ui/src/router.tsx
  services/system/Accounts/ui/tailwind.config.js
  services/system/Accounts/ui/tsconfig.app.json
  services/system/Accounts/ui/tsconfig.json
  services/system/Accounts/ui/tsconfig.node.json
  services/system/Accounts/ui/vite.config.ts
  services/system/Accounts/ui/yarn.lock
  services/user/CommonApi/common/packages/common-lib/src/supervisor.ts
  services/user/Homepage/ui/package.json
  services/user/Homepage/ui/src/components/settings-dropdown.tsx
  services/user/Homepage/ui/src/lib/hooks/useCreateConnectionToken.ts
  services/user/Homepage/ui/src/lib/hooks/useCurrentAccounts.ts
  services/user/Homepage/ui/src/lib/hooks/useGenerateInvite.ts
  services/user/Homepage/ui/src/lib/hooks/useLoggedInUser.ts
  services/user/Homepage/ui/src/lib/hooks/useLogout.ts
  services/user/Homepage/ui/src/lib/hooks/useSelectAccount.ts
  services/user/Homepage/ui/src/lib/hooks/useSupervisor.ts
  services/user/Homepage/ui/src/main.tsx
  services/user/Homepage/ui/src/pages/Invite.tsx
  services/user/Homepage/ui/src/pages/InviteResponse.tsx
  services/user/Homepage/ui/src/router.tsx
  services/user/Homepage/ui/yarn.lock
  services/user/Invite/plugin/src/lib.rs
Labels: System app

#956 support private key extraction from auth-sig
  services/system/AuthSig/plugin/src/helpers.rs
  services/system/AuthSig/plugin/src/lib.rs
  services/system/AuthSig/plugin/wit/world.wit
Labels: System app

#957 Rework staged tx
  rust/psibase/src/services/transact.rs
  services/system/AuthAny/include/services/system/AuthAny.hpp
  services/system/AuthAny/src/AuthAny.cpp
  services/system/AuthSig/include/services/system/AuthSig.hpp
  services/system/AuthSig/src/AuthSig.cpp
  services/system/StagedTx/service/Cargo.toml
  services/system/StagedTx/service/cpp/include/services/system/StagedTx.hpp
  services/system/StagedTx/service/src/lib.rs
  services/system/Transact/include/services/system/Transact.hpp
Labels: System app

#959 cargo-psibase fixes/improvements
  rust/cargo-psibase/src/main.rs
Labels: Dev Experience

#943 wasm32-wasi -> wasm32-wasip1
  .github/workflows/ubuntu-builder.yml
  CMakeLists.txt
  README.md
  doc/psidk/src/development/services/rust-service/setup.md
  libraries/psibase/CMakeLists.txt
  libraries/psibase/sdk/pack_service.cmake
  libraries/psibase/sdk/psibase-config.cmake
  libraries/psibase/sdk/psibase-config.cmake.build
  libraries/psibase/sdk/rs-components.cmake
  libraries/psibase/sdk/toolchain.cmake
  rust/cargo-psibase/src/main.rs
  rust/cargo-psibase/src/package.rs
  wasm/CMakeLists.txt
  wasm/toolchain.cmake
Labels: no-log

#952 auth-delegate support staged tx
  services/system/AuthDelegate/CMakeLists.txt
  services/system/AuthDelegate/include/services/system/AuthDelegate.hpp
  services/system/AuthDelegate/src/AuthDelegate.cpp
  services/system/AuthDelegate/test/CMakeLists.txt
  services/system/AuthDelegate/test/src/AuthDelegate-test.cpp
  services/system/AuthSig/test/src/AuthSig-test.cpp
Labels: System app

#963 Add manual plugin tester interface
  CMakeLists.txt
  dev/demoapp1-build-and-deploy.sh
  services/user/CommonApi/common/packages/common-lib/src/index.ts
  services/user/CommonApi/common/packages/common-lib/src/messaging/FunctionCallRequest.ts
  services/user/CommonApi/common/packages/common-lib/src/messaging/FunctionCallResponse.ts
  services/user/CommonApi/common/packages/common-lib/src/messaging/GetJsonRequest.ts
  services/user/CommonApi/common/packages/common-lib/src/messaging/PluginId.ts
  services/user/CommonApi/common/packages/common-lib/src/messaging/PreLoadPluginsRequest.ts
  services/user/CommonApi/common/packages/common-lib/src/messaging/index.ts
  services/user/CommonApi/common/packages/common-lib/src/supervisor.ts
  services/user/CommonApi/common/packages/common-lib/src/utils.ts
  services/user/CommonApi/common/packages/plugin-tester/ui/.eslintrc.cjs
  services/user/CommonApi/common/packages/plugin-tester/ui/.gitignore
  services/user/CommonApi/common/packages/plugin-tester/ui/index.html
  services/user/CommonApi/common/packages/plugin-tester/ui/package.json
  services/user/CommonApi/common/packages/plugin-tester/ui/src/App.css
  services/user/CommonApi/common/packages/plugin-tester/ui/src/App.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/LoginBar.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/PluginLoader.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/ExecutionTabs.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/FunctionSelector.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/InterfaceTabs.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/ServiceInput.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/hooks/usePluginSchema.ts
  services/user/CommonApi/common/packages/plugin-tester/ui/src/index.css
  services/user/CommonApi/common/packages/plugin-tester/ui/src/main.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/types.ts
  services/user/CommonApi/common/packages/plugin-tester/ui/src/utils.ts
  services/user/CommonApi/common/packages/plugin-tester/ui/src/vite-env.d.ts
  services/user/CommonApi/common/packages/plugin-tester/ui/tsconfig.json
  services/user/CommonApi/common/packages/plugin-tester/ui/tsconfig.node.json
  services/user/CommonApi/common/packages/plugin-tester/ui/vite.config.ts
  services/user/CommonApi/common/packages/plugin-tester/ui/yarn.lock
  services/user/Invite/plugin/src/types.rs
  services/user/Supervisor/ui/src/appInterace.ts
  services/user/Supervisor/ui/src/callStack.ts
  services/user/Supervisor/ui/src/main.ts
  services/user/Supervisor/ui/src/plugin/plugin.ts
  services/user/Supervisor/ui/src/plugin/pluginHost.ts
  services/user/Supervisor/ui/src/plugin/pluginLoader.ts
  services/user/Supervisor/ui/src/supervisor.ts
  services/user/Supervisor/ui/src/utils.ts
Labels: Dev Experience
