Repository gofractally/psibase, pull requests merged in 2024-05, with the labels that each got.

#698 Relax the single-threaded timer accuracy test
  libraries/psibase/native/tests/WatchdogTests.cpp
Labels: no-log

#700 Add timeout after shutdown. Fixes #692.
  programs/psinode/tests/psinode.py
Labels: bug

#703 Trigger a view change when enough joint producers advance
  doc/psidk/src/specifications/blockchain/peer-consensus/joint-consensus.md
  libraries/net/include/psibase/bft.hpp
  libraries/net/test/test_bft_consensus.cpp
Labels: bug, Node infra

#706 Handle AccountNumbers as query keys
  libraries/psibase/common/include/psibase/AccountNumber.hpp
  libraries/psibase/common/include/psibase/schema.hpp
  libraries/psio/include/psio/schema.hpp
  libraries/psio/src/schema.cpp
  services/user/Events/src/REvents.cpp
  services/user/Events/src/types.cpp
  services/user/Events/test/EventsTest.cpp
  services/user/Events/test/TestService.cpp
  services/user/Events/test/TestService.hpp
Labels: Dev Experience

#707 misc doc updates
  doc/psidk/src/SUMMARY.md
  doc/psidk/src/specifications/app-architecture/plugins.md
  doc/psidk/src/specifications/app-architecture/supervisor.md
  doc/psidk/src/specifications/blockchain/README.md
  doc/psidk/src/specifications/blockchain/database.md
  doc/psidk/src/specifications/data-formats/account-numbers.md
Labels: documentation, Dev Experience

#708 improve misc error messages
  libraries/psibase/native/src/ExecutionContext.cpp
  libraries/psibase/native/src/pkcs11.cpp
Labels: no-log

#713 Improve token service graphql queries
  .vscode/tasks.json.sample
  libraries/psibase/common/include/psibase/db.hpp
  libraries/psibase/common/include/psibase/serveGraphQL.hpp
  programs/psinode/tests/test_psibase.py
  services/user/Tokens/include/services/user/tokenTables.hpp
  services/user/Tokens/src/RTokens.cpp
  services/user/XAdmin/ui/yarn.lock
Labels: System app

#721 qualify all std::move calls
  services/system/AuthK1/src/RAuthK1.cpp
  services/user/Fractal/src/Fractal.cpp
  services/user/Invite/src/Invite.cpp
Labels: no-log

#723 Add `userTokens` query
  services/user/Tokens/src/RTokens.cpp
Labels: System app

#724 minor token query cleanup
  services/user/Tokens/src/RTokens.cpp
Labels: no-log

#718 Reduce system token precision
  libraries/psio/include/psio/from_json.hpp
  services/user/Fractal/test/src/manual-fractal-test.cpp
  services/user/Symbol/src/Symbol.cpp
  services/user/Symbol/test/src/Symbol-test.cpp
  services/user/Tokens/include/services/user/tokenTypes.hpp
  services/user/Tokens/src/RTokens.cpp
  services/user/Tokens/src/TokenUsers.json
  services/user/Tokens/src/Tokens.cpp
  services/user/Tokens/test/src/Tokens-test.cpp
Labels: System app

#719 Add `SplitKey` type for subindexing in token query service
  services/user/Tokens/include/services/user/tokenTables.hpp
  services/user/Tokens/src/RTokens.cpp
Labels: Dev Experience

#729 bump version
  CMakeLists.txt
  dev/DemoApp1/service/Cargo.toml
  libraries/psibase/common/include/psibase/version.hpp
  rust/Cargo.lock
  rust/Cargo.toml
  rust/burst-transfer/Cargo.toml
  rust/cargo-psibase/Cargo.toml
  rust/fracpack/Cargo.toml
  rust/psibase/Cargo.toml
  rust/psibase_macros/Cargo.toml
  rust/test_contract/Cargo.toml
  rust/test_contract_2/Cargo.toml
  rust/test_fracpack/Cargo.toml
  rust/test_service_elections/Cargo.toml
  rust/test_service_sites/Cargo.toml
  services/user/Invite/plugin/Cargo.lock
  services/user/XAdmin/ui/yarn.lock
Labels: no-log

#725 Move cpp WASI polyfills from tester to psitest cli
  libraries/psibase/CMakeLists.txt
  libraries/psibase/tester/src/wasi_polyfill/__wasi_args_get.cpp
  libraries/psibase/tester/src/wasi_polyfill/__wasi_args_sizes_get.cpp
  libraries/psibase/tester/src/wasi_polyfill/__wasi_clock_time_get.cpp
  libraries/psibase/tester/src/wasi_polyfill/__wasi_environ_get.cpp
  libraries/psibase/tester/src/wasi_polyfill/__wasi_environ_sizes_get.cpp
  libraries/psibase/tester/src/wasi_polyfill/__wasi_fd_close.cpp
  libraries/psibase/tester/src/wasi_polyfill/__wasi_fd_fdstat_get.cpp
  libraries/psibase/tester/src/wasi_polyfill/__wasi_fd_fdstat_set_flags.cpp
  libraries/psibase/tester/src/wasi_polyfill/__wasi_fd_filestat_get.cpp
  libraries/psibase/tester/src/wasi_polyfill/__wasi_fd_prestat_dir_name.cpp
  libraries/psibase/tester/src/wasi_polyfill/__wasi_fd_prestat_get.cpp
  libraries/psibase/tester/src/wasi_polyfill/__wasi_fd_read.cpp
  libraries/psibase/tester/src/wasi_polyfill/__wasi_fd_readdir.cpp
  libraries/psibase/tester/src/wasi_polyfill/__wasi_fd_seek.cpp
  libraries/psibase/tester/src/wasi_polyfill/__wasi_fd_write.cpp
  libraries/psibase/tester/src/wasi_polyfill/__wasi_path_filestat_get.cpp
  libraries/psibase/tester/src/wasi_polyfill/__wasi_path_open.cpp
  libraries/psibase/tester/src/wasi_polyfill/__wasi_proc_exit.cpp
  programs/psitest/main.cpp
Labels: Dev Experience
