Repository gofractally/psibase, pull requests merged in 2024-06, with the labels that each got.

#726 Rust Fracpack: Omit trailing optionals
  rust/burst-transfer/src/main.rs
  rust/fracpack/src/fracpack.rs
  rust/psibase_macros/src/fracpack_macro.rs
  rust/test_fracpack/src/lib.rs
  rust/test_fracpack/tests/test.cpp
  rust/test_fracpack/tests/test.hpp
  rust/test_fracpack/tests/test.rs
Labels: Dev Experience

#722 Update nft service
  CMakeLists.txt
  services/user/Nft/include/services/user/Nft.hpp
  services/user/Nft/include/services/user/nftTables.hpp
  services/user/Nft/src/Nft.cpp
  services/user/Nft/test/src/Nft-test.cpp
Labels: System app

#727 Fix & update rust tester
  libraries/psibase/tester/src/tester.cpp
  rust/cargo-psibase/build.rs
  rust/cargo-psibase/src/main.rs
  rust/cargo-psibase/tester_wasi_polyfill/Cargo.lock
  rust/cargo-psibase/tester_wasi_polyfill/Cargo.toml.in
  rust/cargo-psibase/tester_wasi_polyfill/src/lib.rs
  rust/psibase/src/block.rs
  rust/psibase/src/native_tables.rs
  rust/psibase/src/tester.rs
  rust/psibase/src/tester_raw.rs
  rust/psibase_macros/src/test_case_macro.rs
  rust/test_contract_2/src/lib.rs
Labels: Dev Experience

#738 fix warning
  services/user/Nft/src/Nft.cpp
Labels: no-log

#768 Prepare for cargo component update
  dev/DemoApp1/plugin/Cargo.lock
  dev/DemoApp1/plugin/Cargo.toml
  dev/DemoApp1/service/Cargo.lock
  dev/DemoApp2/plugin/Cargo.lock
  dev/DemoApp2/plugin/Cargo.toml
  services/system/Accounts/plugin/Cargo.lock
  services/system/Accounts/plugin/Cargo.toml
  services/system/AuthSig/plugin/Cargo.lock
  services/system/AuthSig/plugin/Cargo.toml
  services/user/CommonApi/common/packages/component-parser/Cargo.lock
  services/user/CommonApi/common/packages/component-parser/Cargo.toml
  services/user/CommonApi/common/packages/component-parser/src/lib.rs
  services/user/Invite/plugin/Cargo.lock
  services/user/Invite/plugin/Cargo.toml
  services/user/Tokens/plugin/Cargo.toml
Labels: no-log

#739 Implement new subjective database access
  CMakeLists.txt
  doc/psidk/src/development/services/cpp-service/reference/native-functions.md
  doc/psidk/src/development/services/cpp-service/reference/table.md
  libraries/psibase/common/include/psibase/RawNativeFunctions.hpp
  libraries/psibase/common/include/psibase/Table.hpp
  libraries/psibase/common/include/psibase/db.hpp
  libraries/psibase/native/include/psibase/ActionContext.hpp
  libraries/psibase/native/include/psibase/NativeFunctions.hpp
  libraries/psibase/native/include/psibase/db.hpp
  libraries/psibase/native/src/ExecutionContext.cpp
  libraries/psibase/native/src/NativeFunctions.cpp
  libraries/psibase/native/src/useTriedent.cpp
  libraries/psibase/tester/include/psibase/tester.hpp
  libraries/psibase_http/http.cpp
  programs/psinode/CMakeLists.txt
  programs/psinode/tests/fracpack.py
  programs/psinode/tests/psinode.py
  programs/psinode/tests/test_subjective.py
  programs/psinode/tests/testutil.py
  programs/psitest/main.cpp
  rust/CMakeLists.txt
  rust/Cargo.lock
  rust/Cargo.toml
  rust/cargo-psibase/src/main.rs
  rust/gen-cpp-doc/src/main.rs
  rust/psibase/Cargo.toml
  rust/psibase/src/native.rs
  rust/psibase/src/native_raw.rs
  rust/psibase/src/table.rs
  rust/psibase_macros/src/service_macro.rs
  rust/test_subjective/Cargo.toml
  rust/test_subjective/src/lib.rs
  services/psibase_tests/CMakeLists.txt
  services/psibase_tests/CounterService.cpp
  services/psibase_tests/ParallelSubjectiveService.cpp
  services/psibase_tests/subjective-service.cpp
  services/psibase_tests/subjective-service.hpp
  services/psibase_tests/test_subjective.cpp
  services/system/Accounts/plugin/Cargo.lock
  services/system/AuthSig/plugin/Cargo.lock
  services/user/Invite/plugin/Cargo.lock
Labels: Node infra
