Repository gofractally/psibase, pull requests merged in 2024-03, with the labels that each got.

#632 increment version to 0.7.0
  CMakeLists.txt
  libraries/psibase/common/include/psibase/version.hpp
  rust/Cargo.lock
  rust/Cargo.toml
  services/user/AdminSys/ui/yarn.lock
Labels: no-log

#636 generate wasm compile-commands.json
  wasm/CMakeLists.txt
Labels: Dev Experience

#644 move cargo tests into subdirectory
  CMakeLists.txt
  rust/CMakeLists.txt
Labels: no-log

#657 Fix crate versions
  rust/Cargo.lock
  rust/Cargo.toml
  rust/account_sys/.cargo/config.toml
  rust/account_sys/Cargo.toml
  rust/account_sys/src/lib.rs
  rust/burst-transfer/Cargo.toml
  rust/cargo-psibase/Cargo.toml
  rust/fracpack/Cargo.toml
  rust/psibase/Cargo.toml
  rust/psibase_macros/Cargo.toml
  rust/psibase_names/Cargo.toml
  rust/test_contract/Cargo.toml
  rust/test_contract_2/Cargo.toml
  rust/test_fracpack/Cargo.toml
  rust/test_service_elections/Cargo.toml
  rust/test_service_psispace/Cargo.toml
Labels: no-log

#661 Fix cmake copy_directory failure when switching branches.
  libraries/psibase/sdk/pack_service.cmake
Labels: bug, Dev Experience

#674 Remove applet related libraries
  CMakeLists.txt
  dev/DemoApp1/ui/vite.config.ts
  services/system/AuthEcSys/ui/README.md
  services/system/AuthEcSys/ui/index.html
  services/system/AuthEcSys/ui/index.js
  services/user/AdminSys/ui/README.md
  services/user/AdminSys/ui/src/helpers.ts
  services/user/AdminSys/ui/vite.config.ts
  services/user/CommonSys/CMakeLists.txt
  services/user/CommonSys/common/packages/common-lib/src/rpc.ts
  services/user/CommonSys/common/packages/common-lib/vite.config.ts
  services/user/CommonSys/common/packages/wasm-loader/vite.config.ts
  services/user/CommonSys/ui/README.md
  services/user/CommonSys/ui/index.html
  services/user/CommonSys/ui/src/App.tsx
  services/user/CommonSys/ui/src/components/button.tsx
  services/user/CommonSys/ui/src/components/heading.tsx
  services/user/CommonSys/ui/src/components/icon.tsx
  services/user/CommonSys/ui/src/components/icons/generic/index.ts
  services/user/CommonSys/ui/src/components/icons/generic/loader.svg
  services/user/CommonSys/ui/src/components/icons/index.ts
  services/user/CommonSys/ui/src/components/index.ts
  services/user/CommonSys/ui/src/components/loader.tsx
  services/user/CommonSys/ui/src/components/text.tsx
  services/user/CommonSys/ui/src/config.ts
  services/user/CommonSys/ui/src/helpers.ts
  services/user/CommonSys/ui/src/hooks/useApplets.tsx
  services/user/CommonSys/ui/src/hooks/useEffectOnce.tsx
  services/user/CommonSys/ui/src/images/app-account-desktop.svg
  services/user/CommonSys/ui/src/images/app-account-mobile.svg
  services/user/CommonSys/ui/src/images/app-explore-desktop.svg
  services/user/CommonSys/ui/src/images/app-explore-mobile.svg
  services/user/CommonSys/ui/src/images/app-psibase-desktop.svg
  services/user/CommonSys/ui/src/images/app-psibase-mobile.svg
  services/user/CommonSys/ui/src/images/app-psispace-desktop.svg
  services/user/CommonSys/ui/src/images/app-psispace-mobile.svg
  services/user/CommonSys/ui/src/images/app-wallet-desktop.svg
  services/user/CommonSys/ui/src/images/app-wallet-mobile.svg
  services/user/CommonSys/ui/src/images/ninebox.svg
  services/user/CommonSys/ui/src/images/psibase.svg
  services/user/CommonSys/ui/src/index.d.ts
  services/user/CommonSys/ui/src/main.tsx
  services/user/CommonSys/ui/src/styles/globals.css
  services/user/CommonSys/ui/src/styles/loader.css
  services/user/CommonSys/ui/src/types.ts
  services/user/CommonSys/ui/src/views/applet.tsx
  services/user/CommonSys/ui/src/views/dashboard.tsx
  services/user/CommonSys/ui/src/views/index.ts
  services/user/CommonSys/ui/src/views/nav.tsx
  services/user/CommonSys/ui/vite.config.ts
  services/user/ExploreSys/ui/src/app.html
  services/user/ExploreSys/ui/src/routes/+page.svelte
  services/user/ExploreSys/ui/src/routes/account/[name]/+page.svelte
  services/user/ExploreSys/ui/vite.config.ts
  services/user/SupervisorSys/ui/vite.config.ts
Labels: Refactoring

#672 Additional account name restrictions
  services/system/AccountSys/src/AccountSys.cpp
  services/user/InviteSys/test/src/InviteSys-test.cpp
Labels: Dev Experience
