Repository gofractally/psibase, pull requests merged in 2025-07, with the labels that each got.

#1265 Make flush=true the default for file loggers and also apply it to console.
  doc/psidk/src/run-infrastructure/configuration/logging.md
  libraries/psibase/native/src/log.cpp
Labels: Node infra

#1262 Avoid unpacking and repacking traces in onBlock
  libraries/psibase/common/include/psibase/Table.hpp
  libraries/psio/include/psio/reflect.hpp
  libraries/psio/include/psio/shared_view_ptr.hpp
  libraries/psio/include/psio/view.hpp
  services/system/Transact/src/RTransact.cpp
Labels: Node infra

#1272 Fix BUILD_DEBUG_WASM
  services/system/Transact/CMakeLists.txt
Labels: no-log

#1264 Resize database on startup to match database-cache-size
  libraries/psibase/native/src/Socket.cpp
  libraries/triedent/include/triedent/file_fwd.hpp
  libraries/triedent/include/triedent/mapping.hpp
  libraries/triedent/include/triedent/ring_allocator.hpp
  libraries/triedent/src/cache_allocator.cpp
  libraries/triedent/src/database.cpp
  libraries/triedent/src/mapping.cpp
  programs/psinode/CMakeLists.txt
  programs/psinode/main.cpp
  programs/psinode/tests/test_config.py
Labels: Node infra

#1271 Remove awaiting for state change
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/use-logout.ts
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/use-select-account.ts
  services/system/Accounts/ui/src/hooks/useCreateAccount.ts
  services/system/Accounts/ui/src/hooks/useImportAccount.ts
  services/system/Accounts/ui/src/hooks/useRejectInvite.ts
  services/system/AuthSig/ui/src/hooks/useSelectAccount.ts
  services/system/Producers/ui/src/hooks/use-select-account.ts
  services/system/Producers/ui/src/hooks/useLogout.ts
  services/system/Producers/ui/src/lib/globals.ts
  services/user/Branding/ui/src/hooks/use-select-account.ts
  services/user/Branding/ui/src/hooks/useLogout.ts
  services/user/Branding/ui/src/lib/globals.ts
  services/user/Evaluations/ui/src/hooks/app/use-create-evaluation.ts
  services/user/Evaluations/ui/src/hooks/use-logout.ts
  services/user/Homepage/ui/src/apps/chainmail/components/compose-dialog.tsx
  services/user/Homepage/ui/src/apps/contacts/components/edit-profile-dialog.tsx
  services/user/Homepage/ui/src/apps/contacts/hooks/use-create-contact.ts
  services/user/Homepage/ui/src/apps/contacts/hooks/use-remove-avatar.ts
  services/user/Homepage/ui/src/apps/contacts/hooks/use-set-profile.ts
  services/user/Homepage/ui/src/apps/tokens/page.tsx
  services/user/Homepage/ui/src/globals.ts
  services/user/Homepage/ui/src/hooks/use-logout.ts
  services/user/Homepage/ui/src/hooks/use-select-account.ts
  services/user/Homepage/ui/src/lib/wait.ts
  services/user/Packages/ui/src/hooks/use-logout.ts
  services/user/Permissions/ui/src/hooks/use-select-account.ts
  services/user/Workshop/ui/src/hooks/use-create-app.ts
  services/user/Workshop/ui/src/hooks/use-remove-path.ts
  services/user/Workshop/ui/src/hooks/use-select-account.ts
  services/user/Workshop/ui/src/hooks/useDeleteCsp.ts
  services/user/Workshop/ui/src/hooks/useLogout.ts
  services/user/Workshop/ui/src/hooks/useMail.ts
  services/user/Workshop/ui/src/hooks/useSetMetadata.ts
  services/user/Workshop/ui/src/hooks/useSetServiceCode.ts
  services/user/Workshop/ui/src/hooks/useUploadTree.ts
  services/user/Workshop/ui/src/lib/globals.ts
Labels: System app

#1295 Fix test failure in test_txqueue
  programs/psinode/tests/psinode.py
  programs/psinode/tests/services.py
  programs/psinode/tests/test_txqueue.py
Labels: no-log

#1306 declutter console
  services/system/Transact/plugin/src/helpers.rs
Labels: no-log

#1309 fix warnings in fractals service
  services/user/Fractals/service/src/scoring.rs
  services/user/Fractals/service/src/tables.rs
Labels: System app, no-log

#1312 Adding .tmp/ to excluded dirs when rebuilding
  services/build.shared.mjs
Labels: no-log

#1315 Fix database corruption caused by reusing memory that a session is accessing
  libraries/triedent/include/triedent/gc_queue.hpp
  libraries/triedent/include/triedent/region_allocator.hpp
  libraries/triedent/src/gc_queue.cpp
  libraries/triedent/src/region_allocator.cpp
Labels: bug, Node infra

#1317 Plugin-tester pure formatting changes
  services/user/CommonApi/common/packages/plugin-tester/ui/package.json
  services/user/CommonApi/common/packages/plugin-tester/ui/src/App.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/LoginBar.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/NumericConstraints.ts
  services/user/CommonApi/common/packages/plugin-tester/ui/src/PluginLoader.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/RpcUtils.ts
  services/user/CommonApi/common/packages/plugin-tester/ui/src/StringUtils.ts
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/ExecutionTabs.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/FunctionSelector.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/ParameterEditor.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/ParametersSection.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/ServiceInput.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/TabButton.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/TabControl.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/editors/RawParameterEditor.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/editors/RichParameterEditor.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/BooleanInput.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/ByteListInput.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/CharInput.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/EnumInput.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/FlagsInput.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/ListInput.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/NumberInput.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/OptionalInput.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/RecordInput.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/StringInput.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/TupleInput.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/TypeBasedInput.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/VariantInput.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/bytelist-encodings/Base64Input.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/bytelist-encodings/EncodingSelector.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/bytelist-encodings/FileInput.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/bytelist-encodings/HexInput.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/bytelist-encodings/Utf8Input.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/hooks/usePluginSchema.ts
  services/user/CommonApi/common/packages/plugin-tester/ui/src/main.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/types.ts
  services/user/CommonApi/common/packages/plugin-tester/ui/src/utils.ts
Labels: System app, no-log

#1318 Replace wasi keyvalue shim
  doc/src/specifications/app-architecture/plugins.md
  services/Cargo.lock
  services/system/Accounts/plugin/account_tokens/Cargo.toml
  services/system/Accounts/plugin/account_tokens/src/lib.rs
  services/system/Transact/plugin/Cargo.toml
  services/system/Transact/plugin/src/db.rs
  services/user/ClientData/README.md
  services/user/ClientData/plugin/Cargo.toml
  services/user/ClientData/plugin/src/lib.rs
  services/user/ClientData/plugin/src/tests.rs
  services/user/ClientData/plugin/wit/impl.wit
  services/user/CommonApi/common/packages/plugin-tester/ui/vite.config.ts
  services/user/CommonApi/common/packages/wit/wasi-keyvalue.wit
  services/user/Host/plugin/common/Cargo.toml
  services/user/Host/plugin/common/src/bucket.rs
  services/user/Host/plugin/common/src/lib.rs
  services/user/Host/plugin/common/wit/deps/supervisor.wit
  services/user/Host/plugin/common/wit/impl.wit
  services/user/Host/plugin/common/wit/world.wit
  services/user/Supervisor/ui/src/component-loading/loader.ts
  services/user/Supervisor/ui/src/component-loading/privileged-api.js
  services/user/Supervisor/ui/src/component-loading/shims/README.md
  services/user/Supervisor/ui/src/component-loading/shims/ts/wasi-keyvalue.ts
  services/user/Supervisor/ui/src/component-loading/shims/wasi-keyvalue.js
  services/user/Supervisor/ui/src/hostInterface.ts
  services/user/Supervisor/ui/src/plugin/pluginHost.ts
Labels: System app

#1332 add pack/unpack to cpp precision type
  services/user/Tokens/include/services/user/tokenTypes.hpp
Labels: no-log

#1328 Reduce memory usage of RTransact::onTrx
  CMakeLists.txt
  libraries/psibase/common/include/psibase/Table.hpp
  libraries/psio/include/psio/fracpack.hpp
  libraries/psio/include/psio/shared_view_ptr.hpp
  libraries/psio/include/psio/view.hpp
  services/system/Transact/include/services/system/RTransact.hpp
  services/system/Transact/src/RTransact.cpp
Labels: Node infra

#1331 Add unpack to rust 'Precision'
  Testing/Temporary/CTestCostData.txt
  rust/psibase/src/services/tokens/decimal.rs
  rust/psibase/src/services/tokens/mod.rs
  rust/psibase/src/services/tokens/precision.rs
  rust/psibase/src/services/tokens/quantity.rs
  services/user/Symbol/src/Symbol.cpp
  services/user/Symbol/test/src/Symbol-test.cpp
  services/user/Tokens/include/services/user/Tokens.hpp
  services/user/Tokens/include/services/user/tokenTables.hpp
  services/user/Tokens/include/services/user/tokenTypes.hpp
  services/user/Tokens/plugin/src/lib.rs
  services/user/Tokens/service/src/lib.rs
  services/user/Tokens/service/src/tables.rs
  services/user/Tokens/service/src/tests.rs
Labels: no-log

#1311 Publish packages faster
  rust/psibase/src/main.rs
Labels: Dev Experience

#1338 BFT: don't get stuck when there is a view change before we unlock our keys
  .github/workflows/ubuntu-builder.yml
  libraries/net/include/psibase/bft.hpp
  libraries/net/include/psibase/blocknet.hpp
  programs/psinode/CMakeLists.txt
  programs/psinode/main.cpp
  programs/psinode/tests/predicates.py
  programs/psinode/tests/psinode.py
  programs/psinode/tests/test_crash.py
  programs/psinode/tests/testutil.py
Labels: bug, Node infra
