Repository gofractally/psibase, pull requests merged in 2025-05, with the labels that each got.

#1160 Fix assert when accessing sockets from an auth service
  CMakeLists.txt
  libraries/psibase/native/include/psibase/BlockContext.hpp
  libraries/psibase/native/include/psibase/ExecutionContext.hpp
  libraries/psibase/native/include/psibase/NativeFunctions.hpp
  libraries/psibase/native/include/psibase/TransactionContext.hpp
  libraries/psibase/native/src/BlockContext.cpp
  libraries/psibase/native/src/ExecutionContext.cpp
  libraries/psibase/native/src/NativeFunctions.cpp
  libraries/psibase/native/src/TransactionContext.cpp
  libraries/psibase/native/src/VerifyProver.cpp
  libraries/psibase_http/handle_request.cpp
  programs/psinode/tests/test_txqueue.py
  programs/psitest/main.cpp
  services/psibase_tests/CMakeLists.txt
  services/psibase_tests/SocketAuth.cpp
  services/psibase_tests/test_socket.cpp
Labels: bug, Node infra

#1166 Add install status to psibase info output
  programs/psinode/tests/psinode.py
  programs/psinode/tests/test_psibase.py
  rust/psibase/src/main.rs
  rust/psibase/src/package.rs
Labels: Dev Experience

#1167 Make rust semver consistent with C++ for 0.0.x
  rust/psibase/src/semver.rs
  services/psibase_tests/semver.json
Labels: bug, Dev Experience

#1164 fix erroneous dev-dependency in plugin
  package-templates/basic-01/{{project-name | upper_camel_case}}/plugin/Cargo.toml.liquid
Labels: Dev Experience

#1168 Rework alignment merge
  services/user/Evaluations/plugin/src/consensus.rs
  services/user/Evaluations/plugin/src/errors.rs
  services/user/Evaluations/plugin/src/lib.rs
  services/user/Evaluations/plugin/src/tests.rs
  services/user/Evaluations/tests/Cargo.toml
  services/user/Evaluations/tests/src/consensus.rs
  services/user/Evaluations/tests/src/main.rs
Labels: no-log

#1174 Try to fix WatchdogTests
  libraries/psibase/native/tests/CMakeLists.txt
Labels: no-log

#1172 Add option to list packages with updates
  doc/psidk/src/run-infrastructure/cli/psibase.md
  programs/psinode/tests/test_psibase.py
  rust/psibase/src/main.rs
  rust/psibase/src/package.rs
Labels: Dev Experience

#1173 Only redirect GET requests to x-admin
  libraries/psibase_http/handle_request.cpp
  programs/psinode/tests/test_psibase.py
  rust/psibase/src/main.rs
  rust/psibase/src/package.rs
Labels: Dev Experience

#1176 Improve psibase search subcommand
  programs/psinode/tests/test_psibase.py
  rust/psibase/src/main.rs
Labels: Dev Experience

#1183 Remove unused CodeByHashRow::numRefs
  libraries/psibase/common/include/psibase/headerValidation.hpp
  libraries/psibase/common/include/psibase/nativeTables.hpp
  libraries/psibase/native/src/ExecutionContext.cpp
Labels: refactoring, System app

#1179 Fix wrong serialization after empty Option
  libraries/psio/tests/fracpack-tests.json
  libraries/psio/tests/generate_test_data.cpp
  rust/fracpack/src/schema.rs
Labels: bug, Dev Experience

#1181 Add psibase push subcommand
  doc/psidk/src/run-infrastructure/cli/psibase.md
  programs/psinode/tests/test_psibase.py
  rust/psibase/src/main.rs
  rust/psibase/src/package.rs
Labels: Dev Experience

#1188 Remove old fractal service
  CMakeLists.txt
  doc/psidk/src/SUMMARY.md
  doc/psidk/src/default-apps/README.md
  libraries/psibase/CMakeLists.txt
  libraries/psibase/tester/src/DefaultTestChain.cpp
  services/CMakeLists.txt
  services/user/CMakeLists.txt
  services/user/Fractal/CMakeLists.txt
  services/user/Fractal/doc/evaluation.wit
  services/user/Fractal/doc/feature-phases.wit
  services/user/Fractal/doc/fractal-rpc.wit
  services/user/Fractal/doc/fractal-service.wit
  services/user/Fractal/include/services/user/CoreFractal.hpp
  services/user/Fractal/include/services/user/Fractal.hpp
  services/user/Fractal/include/services/user/fractalErrors.hpp
  services/user/Fractal/include/services/user/fractalTables.hpp
  services/user/Fractal/src/CoreFractal.cpp
  services/user/Fractal/src/Fractal.cpp
  services/user/Fractal/test/CMakeLists.txt
  services/user/Fractal/test/src/Fractal-test.cpp
  services/user/Fractal/test/src/manual-fractal-test.cpp
Labels: System app

#1191 Fix TruncSat errors when Rust toolchain is upgraded to 1.87.0
  libraries/psibase/sdk/toolchain.cmake
  programs/psitest/main.cpp
  rust/cargo-psibase/build.rs
  rust/cargo-psibase/src/link.rs
  rust/cargo-psibase/src/main.rs
  rust/cargo-psibase/test-data/README.md
Labels: bug, Dev Experience

#1192 Prepare for upgrade to yarn v4
  .gitignore
  CMakeLists.txt
  services/user/Branding/ui/package.json
  services/user/Branding/yarn.lock
  services/yarn.lock
Labels: no-log

#1194 Fix bugs exposed by gcc-15
  libraries/net/include/psibase/cft.hpp
  programs/psitest/main.cpp
Labels: bug, Node infra

#1196 Fix CMake warnings
  CMakeLists.txt
  libraries/psibase/sdk/pack_service.cmake
  libraries/psibase/sdk/toolchain.cmake
  wasm/toolchain.cmake
Labels: no-log

#1195 Adding login to Branding so it can work
  services/user/Branding/ui/package.json
  services/user/Branding/ui/src/components/settings-dropdown.tsx
  services/user/Branding/ui/src/components/ui/avatar.tsx
  services/user/Branding/ui/src/hooks/use-chain-id.ts
  services/user/Branding/ui/src/hooks/use-connected-accounts.ts
  services/user/Branding/ui/src/hooks/use-select-account.ts
  services/user/Branding/ui/src/hooks/useCreateConnectionToken.ts
  services/user/Branding/ui/src/hooks/useCurrentUser.ts
  services/user/Branding/ui/src/hooks/useExpectCurrentUser.ts
  services/user/Branding/ui/src/hooks/useLogout.ts
  services/user/Branding/ui/src/lib/createIdenticon.ts
  services/user/Branding/ui/src/lib/globals.ts
  services/user/Branding/ui/src/lib/modifyUrlParams.ts
  services/user/Branding/ui/src/lib/zodTypes.ts
  services/user/Branding/ui/src/main.tsx
  services/user/Branding/ui/src/queryClient.ts
  services/user/Branding/ui/src/supervisor.ts
  services/user/Branding/ui/vite.config.ts
Labels: System app

#1197 Adding new vs code settings for yarn workspaces support
  .vscode/settings.json.sample
Labels: Dev Experience

#1154 Publish packages when merging to main
  .github/scripts/make_publisher.sh
  .github/scripts/publish.sh
  .github/workflows/on-update.yml
  .github/workflows/ubuntu-builder.yml
Labels: no-log
