Repository gofractally/psibase, pull requests merged in 2025-02, with the labels that each got.

#1026 Add staged tx plugin
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/use-logged-in-user.ts
  rust/psibase/src/services/mod.rs
  rust/psibase/src/services/staged_tx.rs
  services/system/Accounts/plugin/accounts/src/interfaces/active_app.rs
  services/system/Accounts/plugin/accounts/src/interfaces/api.rs
  services/system/Accounts/plugin/accounts/wit/world.wit
  services/system/AuthSig/ui/src/hooks/useLoggedInUser.ts
  services/system/StagedTx/Cargo.lock
  services/system/StagedTx/Cargo.toml
  services/system/StagedTx/plugin/Cargo.toml
  services/system/StagedTx/plugin/src/db.rs
  services/system/StagedTx/plugin/src/errors.rs
  services/system/StagedTx/plugin/src/lib.rs
  services/system/StagedTx/plugin/wit/impl.wit
  services/system/StagedTx/plugin/wit/world.wit
  services/system/StagedTx/query-service/Cargo.toml
  services/system/StagedTx/query-service/src/lib.rs
  services/system/StagedTx/service/Cargo.toml
  services/system/StagedTx/service/cpp/include/services/system/StagedTx.hpp
  services/system/StagedTx/service/src/db.rs
  services/system/StagedTx/service/src/event.rs
  services/system/StagedTx/service/src/lib.rs
  services/system/Transact/plugin/src/helpers.rs
  services/system/Transact/plugin/src/lib.rs
  services/system/Transact/plugin/wit/impl.wit
  services/system/Transact/plugin/wit/world.wit
  services/user/Branding/plugin/Cargo.toml
  services/user/Branding/plugin/src/lib.rs
  services/user/Branding/plugin/wit/impl.wit
  services/user/Branding/plugin/wit/world.wit
  services/user/Branding/service/src/lib.rs
  services/user/Branding/ui/src/App.tsx
  services/user/Chainmail/plugin/src/lib.rs
  services/user/Chainmail/ui/src/hooks/use-logged-in-user.ts
  services/user/CommonApi/common/packages/plugin-tester/ui/src/LoginBar.tsx
  services/user/CommonApi/common/packages/wit/host-common.wit
  services/user/Homepage/ui/src/lib/hooks/useLoggedInUser.ts
  services/user/Invite/plugin/src/lib.rs
  services/user/Invite/plugin/wit/impl.wit
  services/user/Supervisor/ui/src/supervisor.ts
  services/user/Workshop/ui/src/hooks/useLoggedInUser.ts
Labels: Dev Experience

#1039 Producers plugin
  CMakeLists.txt
  rust/psibase/src/services/producers.rs
  services/Cargo.lock
  services/Cargo.toml
  services/system/Producers/plugin/.gitignore
  services/system/Producers/plugin/Cargo.toml
  services/system/Producers/plugin/src/lib.rs
  services/system/Producers/plugin/wit/impl.wit
  services/system/Producers/plugin/wit/world.wit
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/RecordInput.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/utils.ts
  services/user/XAdmin/ui/src/pages/create-page.tsx
Labels: System app

#1044 Fix psibase warning
  rust/psibase/src/crypto.rs
Labels: Node infra, refactoring

#1048 Allow explicitly specifying subindex key type
  libraries/psibase/common/include/psibase/Table.hpp
  services/psibase_tests/test_table.cpp
Labels: Dev Experience

#1049 View and manage security devices and keys in XAdmin UI
  services/user/XAdmin/ui/src/components/EmptyBlock.tsx
  services/user/XAdmin/ui/src/components/forms/key-device-form.tsx
  services/user/XAdmin/ui/src/components/nav-header.tsx
  services/user/XAdmin/ui/src/configuration/interfaces.ts
  services/user/XAdmin/ui/src/hooks/useBranding.ts
  services/user/XAdmin/ui/src/hooks/useKeyDevices.ts
  services/user/XAdmin/ui/src/lib/chainEndpoints.ts
  services/user/XAdmin/ui/src/lib/keys.ts
  services/user/XAdmin/ui/src/lib/queryKeys.ts
  services/user/XAdmin/ui/src/pages/create-page.tsx
  services/user/XAdmin/ui/src/pages/keys-page.tsx
  services/user/XAdmin/ui/src/routing.tsx
  services/user/XAdmin/ui/src/types.ts
Labels: Node infra

#1053 Fix identity tests
  rust/psibase/src/time.rs
  services/user/Identity/service/src/lib.rs
  services/user/Identity/service/src/tests/errors.rs
  services/user/Identity/service/src/tests/helpers/gql.rs
  services/user/Identity/service/src/tests/helpers/test_helpers.rs
  services/user/Identity/service/src/tests/queries.rs
  services/user/Identity/service/src/tests/stats.rs
Labels: no-log

#1051 Add queries to SetCode and Sites
  .vscode/settings.json.sample
  rust/psibase/src/main.rs
  rust/psibase/src/package.rs
  rust/psibase/src/services/sites.rs
  services/system/SetCode/src/RSetCode.cpp
  services/user/Sites/include/services/user/Sites.hpp
  services/user/Sites/plugin/src/lib.rs
  services/user/Sites/plugin/wit/world.wit
  services/user/Sites/src/Sites.cpp
Labels: System app

#1056 make boot tx packing more consistent
  rust/psibase/src/boot.rs
Labels: Node infra, refactoring

#1055 Use in memory action construction
  services/system/Transact/plugin/src/db.rs
  services/system/Transact/plugin/src/lib.rs
  services/user/ClientData/plugin/src/lib.rs
  services/user/Supervisor/ui/src/callStack.ts
Labels: System app

#1060 allow staged setcode
  services/system/SetCode/plugin/Cargo.toml
  services/system/SetCode/plugin/src/lib.rs
  services/system/SetCode/plugin/wit/impl.wit
  services/system/SetCode/plugin/wit/world.wit
  services/user/Workshop/plugin/src/lib.rs
Labels: no-log

#1057 Fix concurrent push transaction
  libraries/psibase/common/include/psibase/Table.hpp
  libraries/psibase/common/include/psibase/db.hpp
  libraries/psibase/native/include/psibase/db.hpp
  libraries/psibase/native/src/BlockContext.cpp
  libraries/psibase/native/src/NativeFunctions.cpp
  libraries/psibase/native/src/TransactionContext.cpp
  libraries/psibase/native/src/useTriedent.cpp
  programs/psinode/tests/test_query.py
  rust/psibase/src/db.rs
  services/psibase_tests/AsyncQueryService.cpp
  services/system/HttpServer/src/HttpServer.cpp
Labels: bug, Node infra

#1018 docs fixes
  .gitignore
  doc/diagrams/action-scripts.md
  doc/diagrams/import-existing-account.md
  doc/diagrams/operation-breadcrumbs.md
  doc/diagrams/symbol-market.md
  doc/https.md
  doc/psidk/book.toml.in
  doc/psidk/theme/css/chrome.css
  doc/psidk/theme/css/general.css
  doc/psidk/theme/css/highlight.css
  doc/psidk/theme/css/tabs.css
  doc/psidk/theme/css/variables.css
  doc/psidk/theme/favicon.png
  doc/psidk/theme/favicon.svg
  doc/psidk/theme/index.hbs
  doc/psidk/theme/js/app-init.js
  doc/psidk/theme/js/mermaid-load.js
  doc/psidk/theme/js/tabs.js
Labels: documentation, Dev Experience

#1061 Reduce r-transact memory consumption
  services/system/Transact/src/RTransact.cpp
Labels: Node infra

#1079 Fix excessive transaction splitting
  rust/psibase/src/rpc.rs
Labels: bug, Dev Experience

#1076 Restoring module name as attr/param for service_tables_macro
  rust/psibase_macros/psibase-macros-lib/src/service_tables_macro.rs
Labels: Dev Experience
