Repository gofractally/psibase, pull requests merged in 2025-04, with the labels that each got.

#1126 Remove obsolete scripts
  dev/demoapp1-build-and-deploy.sh
  dev/supervisor-build-and-deploy.sh
Labels: no-log

#1127 Help cargo-psibase find psibase even when it isn't in PATH.
  rust/cargo-psibase/src/main.rs
Labels: Dev Experience

#1129 Fixing package-template (which wasn't building)
  package-templates/basic-01/{{project-name | upper_camel_case}}/service/src/lib.rs
Labels: bug, System app

#1131 Remove sslip from docs
  doc/psidk/src/default-apps/docs.md
  doc/psidk/src/development/front-ends/README.md
  doc/psidk/src/development/front-ends/reference/external.md
  doc/psidk/src/development/front-ends/reference/http-requests.md
  doc/psidk/src/development/front-ends/reference/js-libraries.md
  doc/psidk/src/development/services/cpp-service/minimal-ui/README.md
  doc/psidk/src/development/services/rust-service/minimal-ui.md
  doc/psidk/src/development/services/rust-service/tables.md
  doc/psidk/src/run-infrastructure/administration.md
  doc/psidk/src/run-infrastructure/cli/README.md
  doc/psidk/src/run-infrastructure/cli/psibase.md
  rust/burst-transfer/src/main.rs
  rust/psibase/src/main.rs
  services/user/Fractal/test/src/manual-fractal-test.cpp
  services/user/Registry/README.md
Labels: documentation, Node infra

#1132 Remove use of --suppress-ok from cargo-psibase
  rust/cargo-psibase/src/main.rs
Labels: Dev Experience

#1135 add clangd gitignore
  .gitignore
Labels: no-log

#1123 Fractal spec v0.1 proposal
  services/user/Fractal/doc/fractal-rpc.wit
  services/user/Fractal/doc/fractal-service.wit
  services/user/fractally-world.wit
Labels: no-log

#1136 Replace serveSchema with a single endpoint in packages
  doc/psidk/src/development/services/cpp-service/reference/web-services.md
  doc/psidk/src/development/services/rust-service/reference/web-services.md
  libraries/psibase/common/include/psibase/serveSchema.hpp
  libraries/psibase/common/include/psibase/serveSimpleUI.hpp
  package-templates/basic-01/{{project-name | upper_camel_case}}/query-service/src/lib.rs
  programs/psinode/tests/psinode.py
  rust/psibase/src/serve_http.rs
  services/psibase_tests/CounterService.cpp
  services/psibase_tests/SubjectiveCounterService.cpp
  services/psibase_tests/event-service.cpp
  services/system/AuthDelegate/src/RAuthDelegate.cpp
  services/system/Producers/src/RProducers.cpp
  services/system/SetCode/src/RSetCode.cpp
  services/system/StagedTx/query-service/src/lib.rs
  services/system/Transact/src/RTransact.cpp
  services/user/Invite/src/AuthInvite.cpp
  services/user/Packages/include/services/user/Packages.hpp
  services/user/Packages/src/RPackages.cpp
  services/user/Profiles/query-service/src/lib.rs
  services/user/Sites/src/Sites.cpp
Labels: Dev Experience

#1139 loosen restrictions on semver 0.*
  rust/psibase/src/semver.rs
Labels: Dev Experience

#1140 update key import/export
  services/system/Accounts/ui/src/KeyImport.tsx
  services/system/Accounts/ui/src/hooks/useB64.ts
  services/system/Accounts/ui/src/lib/key.ts
  services/system/AuthSig/ui/src/AccountSelection.tsx
  services/system/AuthSig/ui/src/hooks/usePrivateFromPublicKey.ts
  services/system/AuthSig/ui/src/hooks/usePrivateToPublicKey.ts
  services/system/AuthSig/ui/src/lib/key.ts
Labels: System app

#1147 hooks module; secondary index query
  services/user/Evaluations/query-service/src/lib.rs
  services/user/Evaluations/service/src/db.rs
  services/user/Evaluations/service/src/hooks.rs
Labels: no-log

#1145 Allow the account name to differ from the crate name.
  rust/cargo-psibase/src/package.rs
  rust/test_contract/src/lib.rs
Labels: Dev Experience

#1150 Implement on-chain package repository
  doc/psidk/src/run-infrastructure/cli/psibase.md
  programs/psinode/tests/test_psibase.py
  rust/psibase/src/main.rs
  rust/psibase/src/package.rs
  rust/psibase/src/services/packages.rs
  rust/psibase/src/transaction_builder.rs
  services/user/Packages/include/services/user/Packages.hpp
  services/user/Packages/src/Packages.cpp
  services/user/Packages/src/RPackages.cpp
Labels: Dev Experience

#1141 Use JSON instead of hex packed arguments in postinstall scripts
  libraries/psibase/common/include/psibase/MethodNumber.hpp
  libraries/psibase/common/src/schema.cpp
  libraries/psibase/tester/include/psibase/package.hpp
  libraries/psibase/tester/src/DefaultTestChain.cpp
  libraries/psibase/tester/src/package.cpp
  libraries/psio/include/psio/from_json.hpp
  libraries/psio/include/psio/json/any.hpp
  libraries/psio/include/psio/schema.hpp
  libraries/psio/include/psio/shared_view_ptr.hpp
  libraries/psio/include/psio/stream.hpp
  libraries/psio/src/schema.cpp
  libraries/psio/tests/test_chrono.cpp
  libraries/psio/tests/test_fracpack.hpp
  libraries/psio/tests/test_schema.cpp
  package-templates/basic-01/{{project-name | upper_camel_case}}/service/Cargo.toml.liquid
  rust/cargo-psibase/src/package.rs
  rust/fracpack/src/schema.rs
  rust/psibase/src/boot.rs
  rust/psibase/src/main.rs
  rust/psibase/src/package.rs
  rust/psibase/src/schema.rs
  rust/psibase_macros/psibase-macros-lib/src/service_macro/actions.rs
  rust/psibase_macros/psibase-macros-lib/src/service_macro/events.rs
  rust/psibase_macros/psibase-macros-lib/src/service_macro/mod.rs
  rust/test_fracpack/build.rs
  rust/test_package/service/Cargo.toml
  services/system/Producers/src/postinstall.json
  services/system/StagedTx/service/Cargo.toml
  services/system/Transact/src/postinstall.json
  services/user/Chainmail/service/Cargo.toml
  services/user/Events/src/postinstall.json
  services/user/Homepage/postinstall.json
  services/user/Permissions/postinstall.json
  services/user/Workshop/postinstall.json
Labels: Dev Experience

#1148 improve default vscode tasks/scripts
  .vscode/scripts/build.sh
  .vscode/scripts/continue.sh
  .vscode/scripts/launch.sh
  .vscode/scripts/launch_secure.sh
  .vscode/tasks.json.sample
Labels: Dev Experience

#1161 improve subindex doc comment
  rust/psibase/src/graph_ql.rs
Labels: documentation, Dev Experience

#1163 refactor evaluations service
  rust/psibase/src/services/evaluations.rs
  services/user/Evaluations/Cargo.lock
  services/user/Evaluations/query-service/src/lib.rs
  services/user/Evaluations/service/Cargo.toml
  services/user/Evaluations/service/src/db.rs
  services/user/Evaluations/service/src/helpers.rs
  services/user/Evaluations/service/src/hooks.rs
  services/user/Evaluations/service/src/lib.rs
Labels: refactoring, no-log
