Repository gofractally/psibase, pull requests merged in 2025-09, with the labels that each got.

#1402 Improve embedded mode
  packages/user/Host/plugin/common/src/lib.rs
  packages/user/Host/plugin/common/wit/deps/supervisor.wit
  packages/user/Host/plugin/common/wit/world.wit
  packages/user/Supervisor/ui/src/callContext.ts
  packages/user/Supervisor/ui/src/callStack.ts
  packages/user/Supervisor/ui/src/component-loading/privileged-api.js
  packages/user/Supervisor/ui/src/hostInterface.ts
  packages/user/Supervisor/ui/src/plugin/pluginHost.ts
  packages/user/Supervisor/ui/src/plugin/plugins.ts
  packages/user/Supervisor/ui/src/supervisor.ts
Labels: Dev Experience

#1417 fix account import permissions error
  packages/system/AuthSig/plugin/src/lib.rs
Labels: bug, System app

#1413 Convert local service initialization to use packages
  .github/workflows/ubuntu-builder.yml
  CMakeLists.txt
  libraries/psibase/CMakeLists.txt
  libraries/psibase/common/include/psibase/fileUtil.hpp
  libraries/psibase/common/include/psibase/package.hpp
  libraries/psibase/common/include/psibase/semver.hpp
  libraries/psibase/common/include/psibase/zip.hpp
  libraries/psibase/common/src/fileUtil.cpp
  libraries/psibase/common/src/package.cpp
  libraries/psibase/common/src/semver.cpp
  libraries/psibase/common/src/zip.cpp
  libraries/psibase/native/include/psibase/Socket.hpp
  libraries/psibase/native/src/Socket.cpp
  libraries/psibase/tester/include/psibase/tester.hpp
  libraries/psibase/tester/src/DefaultTestChain.cpp
  libraries/psibase/tester/src/tester.cpp
  packages/local/XAdmin/src/XAdmin.cpp
  packages/user/Events/src/EventConfig.cpp
  packages/user/Packages/include/services/user/Packages.hpp
  packages/user/Packages/include/services/user/RPackages.hpp
  packages/user/Packages/src/Packages.cpp
  packages/user/Packages/src/RPackages.cpp
  programs/psinode/CMakeLists.txt
  programs/psinode/init.cpp
  programs/psinode/main.cpp
  programs/psitest/main.cpp
  rust/psibase/src/package.rs
  rust/psibase/src/tester.rs
Labels: Node infra

#1443 Updating bad flag mapping
  rust/psibase/src/package.rs
Labels: bug, Dev Experience

#1449 fix plugin tester
  packages/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/TypeBasedInput.tsx
Labels: bug, System app

#1448 XAdmin: Avoid querying producers unless we've successfully booted
  CMakeLists.txt
  packages/local/XAdmin/ui/src/hooks/useProducers.ts
Labels: Node infra

#1455 Misc cmakelists fixes
  CMakeLists.txt
Labels: no-log

#1453 Add tests for runModeRpc and runModeCallback
  libraries/psibase/native/include/psibase/BlockContext.hpp
  libraries/psibase/native/src/BlockContext.cpp
  libraries/psibase/tester/include/psibase/tester.hpp
  libraries/psibase/tester/include/psibase/testerApi.hpp
  libraries/psibase/tester/src/tester.cpp
  packages/psibase_tests/include/services/test/SubjectiveCounterService.hpp
  packages/psibase_tests/src/SubjectiveCounterService.cpp
  packages/psibase_tests/test/test_subjective.cpp
  programs/psitest/main.cpp
  rust/psibase/src/block.rs
  rust/psibase/src/tester.rs
  rust/psibase/src/tester_raw.rs
Labels: no-log

#1458 Fix typo in error message
  libraries/psio/include/psio/view.hpp
Labels: no-log
