Repository gofractally/psibase, pull requests merged in 2025-01, with the labels that each got.

#967 Add login and account switching to package template
  package-templates/rust/ui/package.json
  package-templates/rust/ui/src/App.tsx
  package-templates/rust/ui/src/components/account-switcher.tsx
  package-templates/rust/ui/src/components/mode-toggle.tsx
  package-templates/rust/ui/src/components/nav.tsx
  package-templates/rust/ui/src/components/settings-dropdown.tsx
  package-templates/rust/ui/src/hooks/index.ts
  package-templates/rust/ui/src/hooks/use-create-connection-token.ts
  package-templates/rust/ui/src/hooks/use-current-accounts.ts
  package-templates/rust/ui/src/hooks/use-logged-in-user.ts
  package-templates/rust/ui/src/hooks/use-logout.ts
  package-templates/rust/ui/src/hooks/use-select-account.ts
  package-templates/rust/ui/src/lib/utils.ts
  package-templates/rust/ui/src/main.tsx
  package-templates/rust/ui/src/shad/components/ui/avatar.tsx
  package-templates/rust/ui/tsconfig.json
  services/user/Branding/yarn.lock
Labels: Dev Experience

#976 Fix cpp graphql schema generation including variants
  libraries/psio/include/psio/graphql.hpp
Labels: bug, Dev Experience

#958 Improve package template
  package-templates/README.md
  package-templates/basic-01/validate-project-name.rhai
  package-templates/basic-01/{{project-name | upper_camel_case}}/Cargo.toml.liquid
  package-templates/basic-01/{{project-name | upper_camel_case}}/README.md
  package-templates/basic-01/{{project-name | upper_camel_case}}/plugin/Cargo.toml.liquid
  package-templates/basic-01/{{project-name | upper_camel_case}}/plugin/src/errors.rs
  package-templates/basic-01/{{project-name | upper_camel_case}}/plugin/src/lib.rs
  package-templates/basic-01/{{project-name | upper_camel_case}}/plugin/wit/impl.wit
  package-templates/basic-01/{{project-name | upper_camel_case}}/plugin/wit/world.wit
  package-templates/basic-01/{{project-name | upper_camel_case}}/query-service/Cargo.toml.liquid
  package-templates/basic-01/{{project-name | upper_camel_case}}/query-service/src/lib.rs
  package-templates/basic-01/{{project-name | upper_camel_case}}/service/Cargo.toml.liquid
  package-templates/basic-01/{{project-name | upper_camel_case}}/service/src/lib.rs
  package-templates/basic-01/{{project-name | upper_camel_case}}/service/src/tests.rs
  package-templates/basic-01/{{project-name | upper_camel_case}}/src/lib.rs
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/.eslintignore
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/.eslintrc.cjs
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/.gitignore
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/README.md
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/components.json
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/index.html
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/package.json
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/postcss.config.cjs
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/prettier.config.cjs
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/App.tsx
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/components/account-switcher.tsx
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/components/index.ts
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/components/mode-toggle.tsx
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/components/nav.tsx
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/components/settings-dropdown.tsx
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/components/theme-provider.tsx
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/index.ts
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/use-create-connection-token.ts
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/use-current-accounts.ts
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/use-logged-in-user.ts
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/use-logout.ts
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/use-select-account.ts
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/lib/utils.ts
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/main.tsx
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/shad/components/ui/avatar.tsx
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/shad/components/ui/button.tsx
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/shad/components/ui/dropdown-menu.tsx
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/shad/components/ui/hover-border-gradient.tsx
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/shad/components/ui/input.tsx
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/shad/components/ui/label.tsx
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/shad/components/ui/separator.tsx
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/shad/components/ui/tabs.tsx
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/shad/components/ui/tooltip.tsx
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/styles/globals.css
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/vite-env.d.ts
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/tailwind.config.cjs
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/tsconfig.json
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/tsconfig.node.json
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/vite.config.ts
  package-templates/cargo-generate.toml
  package-templates/rust/service/src/lib.rs
  package-templates/rust/src/lib.rs
Labels: Dev Experience

#961 Producers support staged tx
  .clang-format
  libraries/psibase/CMakeLists.txt
  libraries/psibase/common/include/psibase/block.hpp
  libraries/psibase/tester/include/psibase/tester.hpp
  programs/psitest/main.cpp
  rust/psibase/src/services/transact.rs
  services/CMakeLists.txt
  services/system/Accounts/include/services/system/Accounts.hpp
  services/system/Accounts/src/Accounts.cpp
  services/system/AuthDelegate/include/services/system/AuthDelegate.hpp
  services/system/AuthDelegate/src/AuthDelegate.cpp
  services/system/AuthSig/src/AuthSig.cpp
  services/system/AuthSig/test/src/AuthSig-test.cpp
  services/system/Producers/CMakeLists.txt
  services/system/Producers/include/services/system/Producers.hpp
  services/system/Producers/src/Producers.cpp
  services/system/Producers/test/CMakeLists.txt
  services/system/Producers/test/src/Producers-test.cpp
  services/system/StagedTx/service/src/lib.rs
  services/system/Transact/include/services/system/Transact.hpp
Labels: System app

#983 Refactor staged tx tables
  .clang-format
  libraries/psibase/CMakeLists.txt
  libraries/psibase/common/include/psibase/block.hpp
  libraries/psibase/tester/include/psibase/tester.hpp
  programs/psitest/main.cpp
  rust/psibase/src/services/transact.rs
  services/CMakeLists.txt
  services/system/Accounts/include/services/system/Accounts.hpp
  services/system/Accounts/src/Accounts.cpp
  services/system/AuthDelegate/include/services/system/AuthDelegate.hpp
  services/system/AuthDelegate/src/AuthDelegate.cpp
  services/system/AuthSig/src/AuthSig.cpp
  services/system/AuthSig/test/src/AuthSig-test.cpp
  services/system/Producers/CMakeLists.txt
  services/system/Producers/include/services/system/Producers.hpp
  services/system/Producers/src/Producers.cpp
  services/system/Producers/test/CMakeLists.txt
  services/system/Producers/test/src/Producers-test.cpp
  services/system/StagedTx/service/src/db.rs
  services/system/StagedTx/service/src/lib.rs
  services/system/StagedTx/service/src/policy.rs
  services/system/Transact/include/services/system/Transact.hpp
  services/user/XAdmin/ui/src/components/forms/confirmation-form.tsx
Labels: Refactoring, no-log

#981 Branding plugin not loading
  services/user/Branding/Cargo.lock
  services/user/Branding/Cargo.toml
  services/user/Branding/plugin/Cargo.toml
  services/user/Branding/service/Cargo.toml
  services/user/Branding/src/lib.rs
  services/user/Sites/src/Sites.cpp
Labels: bug, System app

#980 Improve cpp graphql support
  libraries/psio/include/psio/graphql.hpp
  libraries/psio/tests/graphql.cpp
  services/user/Invite/plugin/src/lib.rs
Labels: Dev Experience

#985 Remove the vestiges of EOS-style keys
  doc/psidk/src/run-infrastructure/cli/psibase.md
  libraries/psibase/CMakeLists.txt
  libraries/psibase/common/include/psibase/crypto.hpp
  libraries/psibase/common/src/crypto.cpp
  libraries/psibase/native/include/psibase/EcdsaProver.hpp
  libraries/psibase/native/src/EcdsaProver.cpp
  libraries/psibase/native/src/PKCS11Prover.cpp
  programs/psinode/main.cpp
  rust/cargo-psibase/src/main.rs
  rust/psibase/src/crypto.rs
Labels: documentation, Dev Experience

#987 allow x-admin to import accounts
  services/system/Accounts/plugin/accounts/src/interfaces/admin.rs
Labels: no-log

#989 Remove db sanityCheck.
  libraries/psibase/native/src/useTriedent.cpp
Labels: Refactoring, no-log

#992 Allow foreign account import into accounts app
  services/system/Accounts/plugin/accounts/src/interfaces/admin.rs
Labels: no-log

#991 Align graphql and json timepointusec serialization
  rust/psibase/src/time.rs
  services/user/Registry/plugin/src/queries.rs
  services/user/Registry/service/src/lib.rs
Labels: Dev Experience

#982 Create and import server key on prod chain boot
  rust/psibase/src/boot.rs
  services/user/XAdmin/ui/src/components/forms/chain-mode-form.tsx
  services/user/XAdmin/ui/src/components/forms/install-form.tsx
  services/user/XAdmin/ui/src/components/multi-step-loader.tsx
  services/user/XAdmin/ui/src/hooks/useAddServerKey.ts
  services/user/XAdmin/ui/src/hooks/useImportAccount.ts
  services/user/XAdmin/ui/src/lib/bootChain.ts
  services/user/XAdmin/ui/src/lib/chainEndpoints.ts
  services/user/XAdmin/ui/src/lib/keys.ts
  services/user/XAdmin/ui/src/lib/queryKeys.ts
  services/user/XAdmin/ui/src/main.tsx
  services/user/XAdmin/ui/src/pages/create-page.tsx
Labels: Node infra

#978 Require table definitions outside of service module
  .gitignore
  doc/psidk/src/development/services/rust-service/graphql.md
  doc/psidk/src/development/services/rust-service/tables.md
  package-templates/basic-01/{{project-name | upper_camel_case}}/service/src/lib.rs
  rust/psibase_macros/psibase-macros-derive/src/lib.rs
  rust/psibase_macros/psibase-macros-lib/src/lib.rs
  rust/psibase_macros/psibase-macros-lib/src/service_macro/mod.rs
  rust/psibase_macros/psibase-macros-lib/src/service_tables_macro.rs
  rust/psibase_macros/psibase-macros-lib/src/service_tables_macro/tables.rs
  rust/test_contract_2/src/lib.rs
  rust/test_psibase_macros/services/add-check-init/src/lib.rs
  rust/test_subjective/src/lib.rs
  services/system/StagedTx/service/src/db.rs
  services/system/StagedTx/service/src/lib.rs
  services/system/StagedTx/service/src/policy.rs
  services/user/Branding/Cargo.toml
  services/user/Branding/service/src/lib.rs
  services/user/Chainmail/service/src/lib.rs
  services/user/Chainmail/service/src/tables.rs
  services/user/Identity/service/src/lib.rs
  services/user/Registry/service/src/lib.rs
Labels: Dev Experience

#993 Build the root of each package
  rust/cargo-psibase/src/main.rs
  rust/cargo-psibase/src/package.rs
  services/user/Chainmail/src/lib.rs
Labels: Dev Experience

#995 use explicit versions in demoapp1
  dev/DemoApp1/plugin/Cargo.toml
  dev/DemoApp1/service/Cargo.lock
  dev/DemoApp1/service/Cargo.toml
Labels: no-log

#994 Use localhost instead of sslip
  doc/psidk/src/run-infrastructure/cli/psinode.md
  libraries/psibase_http/handle_request.cpp
  libraries/psibase_http/http_session_base.hpp
  libraries/psibase_http/include/psibase/http.hpp
  libraries/psibase_http/tls_http_session.hpp
  programs/psinode/config.in
  programs/psinode/main.cpp
  programs/psinode/tests/psinode.py
  rust/Cargo.lock
  rust/psibase/Cargo.toml
  rust/psibase/src/main.rs
  services/Cargo.lock
  services/system/StagedTx/Cargo.lock
  services/user/Branding/Cargo.lock
  services/user/Brotli/Cargo.lock
  services/user/Chainmail/Cargo.lock
  services/user/Registry/Cargo.lock
  services/user/XAdmin/ui/src/configuration/configuration-page.tsx
  services/user/XAdmin/ui/src/configuration/interfaces.ts
  services/user/XAdmin/ui/src/configuration/utils.ts
  services/user/XAdmin/ui/src/hooks/useConfig.ts
Labels: Dev Experience

#1005 add database-cache-size to default psinode config
  programs/psinode/config.in
Labels: Dev Experience

#984 Add Workshop package
  CMakeLists.txt
  services/user/Homepage/ui/src/lib/hooks/useCurrentAccounts.ts
  services/user/Sites/src/Sites.cpp
  services/user/Workshop/ui/components.json
  services/user/Workshop/ui/eslint.config.js
  services/user/Workshop/ui/index.html
  services/user/Workshop/ui/package.json
  services/user/Workshop/ui/postcss.config.js
  services/user/Workshop/ui/src/App.tsx
  services/user/Workshop/ui/src/components/Workshop.tsx
  services/user/Workshop/ui/src/components/error-card.tsx
  services/user/Workshop/ui/src/components/intro-card.tsx
  services/user/Workshop/ui/src/components/metadata-form.tsx
  services/user/Workshop/ui/src/components/nav.tsx
  services/user/Workshop/ui/src/components/settings-dropdown.tsx
  services/user/Workshop/ui/src/components/theme-provider.tsx
  services/user/Workshop/ui/src/components/ui/button.tsx
  services/user/Workshop/ui/src/components/ui/card.tsx
  services/user/Workshop/ui/src/components/ui/dropdown-menu.tsx
  services/user/Workshop/ui/src/components/ui/form.tsx
  services/user/Workshop/ui/src/components/ui/hover-border-gradient.tsx
  services/user/Workshop/ui/src/components/ui/input.tsx
  services/user/Workshop/ui/src/components/ui/label.tsx
  services/user/Workshop/ui/src/components/ui/sonner.tsx
  services/user/Workshop/ui/src/components/ui/spinner.tsx
  services/user/Workshop/ui/src/components/ui/switch.tsx
  services/user/Workshop/ui/src/components/ui/textarea.tsx
  services/user/Workshop/ui/src/hooks/useAppMetadata.ts
  services/user/Workshop/ui/src/hooks/useBranding.ts
  services/user/Workshop/ui/src/hooks/useCreateConnectionToken.ts
  services/user/Workshop/ui/src/hooks/useLoggedInUser.ts
  services/user/Workshop/ui/src/hooks/useLogout.ts
  services/user/Workshop/ui/src/hooks/usePublishApp.ts
  services/user/Workshop/ui/src/hooks/useSetMetadata.ts
  services/user/Workshop/ui/src/index.css
  services/user/Workshop/ui/src/lib/fileToBase64.ts
  services/user/Workshop/ui/src/lib/modifyUrlParams.ts
  services/user/Workshop/ui/src/lib/utils.ts
  services/user/Workshop/ui/src/main.tsx
  services/user/Workshop/ui/src/router.tsx
  services/user/Workshop/ui/tailwind.config.js
  services/user/Workshop/ui/tsconfig.app.json
  services/user/Workshop/ui/tsconfig.json
  services/user/Workshop/ui/tsconfig.node.json
  services/user/Workshop/ui/vite.config.ts
  services/user/Workshop/ui/yarn.lock
Labels: System app

#1013 Simplify making graphql-pagination-style queries for event data
  rust/Cargo.lock
  rust/psibase/src/graph_ql.rs
  rust/psibase/src/time.rs
  rust/test_contract_2/Cargo.toml
  rust/test_contract_2/src/lib.rs
Labels: Dev Experience

#1021 removes unused demoapp2
  dev/DemoApp2/.eslintrc.cjs
  dev/DemoApp2/.gitignore
  dev/DemoApp2/README.md
  dev/DemoApp2/index.html
  dev/DemoApp2/plugin/.gitignore
  dev/DemoApp2/plugin/Cargo.lock
  dev/DemoApp2/plugin/Cargo.toml
  dev/DemoApp2/plugin/src/lib.rs
  dev/DemoApp2/plugin/wit/world.wit
  dev/DemoApp2/ui/.eslintrc.cjs
  dev/DemoApp2/ui/index.html
  dev/DemoApp2/ui/package.json
  dev/DemoApp2/ui/src/App.css
  dev/DemoApp2/ui/src/App.tsx
  dev/DemoApp2/ui/src/index.css
  dev/DemoApp2/ui/src/main.tsx
  dev/DemoApp2/ui/src/vite-env.d.ts
  dev/DemoApp2/ui/tsconfig.json
  dev/DemoApp2/ui/tsconfig.node.json
  dev/DemoApp2/ui/vite.config.ts
  dev/DemoApp2/ui/yarn.lock
  dev/DemoApp2/yarn.lock
  dev/demoapp2-build-and-deploy.sh
  dev/demoapps-build-and-deploy.sh
Labels: System app

#1023 better changelog categories
  .github/workflows/changelog-template.json
  .github/workflows/generate-changelog.yml
Labels: no-log

#1020 remove final references to wasm32-wasi
  dev/demoapp1-build-and-deploy.sh
  libraries/psibase/CMakeLists.txt
  libraries/psibase/sdk/psibase-config.cmake.build
  libraries/psibase/wasm32-wasip1/time.h
  package-templates/README.md
  package-templates/basic-01/{{project-name | upper_camel_case}}/README.md
  rust/cargo-psibase/build.rs
  rust/cargo-psibase/src/main.rs
  rust/cargo-psibase/test-data/README.md
  rust/gen-cpp-doc/src/main.rs
  services/user/Registry/README.md
Labels: refactoring, no-log

#1019 Introduce transact plugin hooks
  doc/psidk/src/specifications/blockchain/smart-authorization.md
  rust/psibase/src/services/http_server.rs
  services/system/Accounts/plugin/smartAuth/README.md
  services/system/Accounts/plugin/smartAuth/export.wit
  services/system/Accounts/plugin/smartAuth/import.wit
  services/system/AuthAny/plugin/Cargo.toml
  services/system/AuthAny/plugin/src/lib.rs
  services/system/AuthAny/plugin/wit/impl.wit
  services/system/AuthDelegate/plugin/Cargo.toml
  services/system/AuthDelegate/plugin/src/lib.rs
  services/system/AuthDelegate/plugin/wit/impl.wit
  services/system/AuthSig/plugin/Cargo.toml
  services/system/AuthSig/plugin/src/lib.rs
  services/system/AuthSig/plugin/wit/impl.wit
  services/system/HttpServer/include/services/system/HttpServer.hpp
  services/system/HttpServer/src/HttpServer.cpp
  services/system/Transact/plugin/Cargo.toml
  services/system/Transact/plugin/src/db.rs
  services/system/Transact/plugin/src/helpers.rs
  services/system/Transact/plugin/src/lib.rs
  services/system/Transact/plugin/src/types.rs
  services/system/Transact/plugin/wit/impl.wit
  services/system/Transact/plugin/wit/world.wit
  services/user/CommonApi/common/packages/common-lib/src/supervisor.ts
  services/user/CommonApi/common/packages/component-parser/Cargo.lock
  services/user/CommonApi/common/packages/component-parser/Cargo.toml
  services/user/CommonApi/common/packages/component-parser/src/lib.rs
  services/user/CommonApi/common/packages/wit/host-common.wit
  services/user/CommonApi/include/services/system/CommonApi.hpp
  services/user/Invite/plugin/src/lib.rs
  services/user/Invite/plugin/wit/impl.wit
  services/user/Invite/plugin_AuthInvite/Cargo.toml
  services/user/Invite/plugin_AuthInvite/src/lib.rs
  services/user/Invite/plugin_AuthInvite/wit/impl.wit
  services/user/Supervisor/ui/src/component-loading/host-api.js
  services/user/Supervisor/ui/src/component-loading/proxy/proxyPackage.ts
  services/user/Supervisor/ui/src/plugin/plugin.ts
  services/user/Supervisor/ui/src/plugin/pluginHost.ts
  services/user/Supervisor/ui/src/plugin/pluginLoader.ts
  services/user/Supervisor/ui/src/supervisor.ts
Labels: Dev Experience

#974 Enable new account creation
  services/system/Accounts/src/Accounts.cpp
  services/system/AuthSig/include/services/system/AuthSig.hpp
  services/system/AuthSig/src/AuthSig.cpp
  services/user/Invite/src/Invite.cpp
  services/user/Invite/test/src/Invite-test.cpp
Labels: refactoring, no-log
