Repository gofractally/psibase, pull requests merged in 2025-08, with the labels that each got.

#1291 Add set-auth-cookie endpoint
  CMakeLists.txt
  libraries/psibase/common/include/psibase/Rpc.hpp
  libraries/psibase/common/include/psibase/webServices.hpp
  libraries/psibase/common/src/Rpc.cpp
  rust/psibase/src/web_services.rs
  services/.pnp.cjs
  services/psibase_tests/test/test_rpc.cpp
  services/system/Accounts/ui/src/AccountSelection.tsx
  services/system/Accounts/ui/src/globals.ts
  services/system/Accounts/ui/src/hooks/use-logout.ts
  services/system/Accounts/ui/src/hooks/useLoginDirect.ts
  services/system/Accounts/ui/src/hooks/useRejectInvite.ts
  services/system/HttpServer/src/HttpServer.cpp
  services/system/Transact/src/RTransact.cpp
  services/user/Branding/plugin/src/errors.rs
  services/user/Branding/plugin/src/lib.rs
  services/user/Branding/service/src/lib.rs
  services/user/CommonApi/common/packages/common-lib/package.json
  services/user/CommonApi/common/packages/common-lib/src/auth-cookie.html
  services/user/CommonApi/common/packages/common-lib/src/auth-cookie.ts
  services/user/CommonApi/common/packages/common-lib/vite.auth-cookie.config.ts
  services/user/CommonApi/common/packages/common-lib/vite.config.ts
  services/user/CommonApi/src/CommonApi.cpp
  services/yarn.lock
  web-apps.cmake
Labels: System app

#1330 Improve permissions plugin
  doc/src/specifications/app-architecture/plugins.md
  services/Cargo.lock
  services/system/Accounts/plugin/accounts/src/interfaces/api.rs
  services/system/AuthSig/plugin/Cargo.toml
  services/system/AuthSig/plugin/src/errors.rs
  services/system/AuthSig/plugin/src/helpers.rs
  services/system/AuthSig/plugin/src/lib.rs
  services/system/AuthSig/plugin/src/risks.rs
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/ExecutionTabs.tsx
  services/user/Host/plugin/common/Cargo.toml
  services/user/Host/plugin/common/src/bucket.rs
  services/user/Host/plugin/common/wit/deps/accounts.wit
  services/user/Host/plugin/common/wit/impl.wit
  services/user/Host/plugin/prompt/src/db.rs
  services/user/Host/plugin/prompt/src/errors.rs
  services/user/Host/plugin/prompt/src/lib.rs
  services/user/Host/plugin/prompt/wit/impl.wit
  services/user/Host/plugin/prompt/wit/world.wit
  services/user/Invite/plugin_AuthInvite/src/lib.rs
  services/user/Permissions/plugin/src/db.rs
  services/user/Permissions/plugin/src/errors.rs
  services/user/Permissions/plugin/src/lib.rs
  services/user/Permissions/plugin/wit/impl.wit
  services/user/Permissions/plugin/wit/world.wit
  services/user/Permissions/ui/src/permissions/App.tsx
Labels: System app

#1342 Set cookie from plugin
  services/system/Accounts/plugin/accounts/src/interfaces/admin.rs
  services/system/Accounts/plugin/accounts/wit/impl.wit
  services/system/Accounts/ui/src/hooks/useLoginDirect.ts
  services/user/CommonApi/src/CommonApi.cpp
  services/user/Supervisor/ui/src/hostInterface.ts
  services/user/Supervisor/ui/src/plugin/pluginHost.ts
Labels: System app

#1353 Output public key as a separate PEM file
  .github/scripts/make_publisher.sh
Labels: no-log

#1351 Cleanup registry app
  packages/system/AuthDelegate/plugin/src/lib.rs
  packages/user/Registry/Cargo.lock
  packages/user/Registry/Cargo.toml
  packages/user/Registry/plugin/src/errors.rs
  packages/user/Registry/plugin/src/lib.rs
  packages/user/Registry/plugin/src/queries.rs
  packages/user/Registry/plugin/src/types.rs
  packages/user/Registry/plugin/wit/impl.wit
  packages/user/Registry/plugin/wit/world.wit
  packages/user/Registry/query/Cargo.toml
  packages/user/Registry/query/src/lib.rs
  packages/user/Registry/service/Cargo.toml
  packages/user/Registry/service/src/constants.rs
  packages/user/Registry/service/src/lib.rs
  packages/user/Registry/service/src/tables.rs
  packages/user/Registry/service/src/tests.rs
  packages/user/Registry/service/src/utils.rs
  packages/user/Workshop/plugin/Cargo.toml
  packages/user/Workshop/plugin/src/lib.rs
  packages/user/Workshop/plugin/wit/impl.wit
  packages/user/Workshop/ui/src/components/app-switcher.tsx
  packages/user/Workshop/ui/src/components/control-panel.tsx
  packages/user/Workshop/ui/src/components/metadata-form.tsx
  packages/user/Workshop/ui/src/hooks/useAppMetadata.ts
  packages/user/Workshop/ui/src/hooks/useSetMetadata.ts
  packages/user/Workshop/ui/src/lib/zodTypes.ts
  packages/user/Workshop/ui/src/pages/Settings.tsx
Labels: System app

#1355 Fix rust service declarations
  packages/user/Invite/include/services/user/AuthInvite.hpp
  packages/user/Invite/src/AuthInvite.cpp
  rust/CMakeLists.txt
  rust/fracpack/src/nested.rs
  rust/fracpack/src/schema.rs
  rust/psibase/src/block.rs
  rust/psibase/src/db.rs
  rust/psibase/src/lib.rs
  rust/psibase/src/schema.rs
  rust/psibase/src/services/accounts.rs
  rust/psibase/src/services/auth_delegate.rs
  rust/psibase/src/services/auth_invite.rs
  rust/psibase/src/services/auth_sig.rs
  rust/psibase/src/services/brotli_codec.rs
  rust/psibase/src/services/chainmail.rs
  rust/psibase/src/services/common_api.rs
  rust/psibase/src/services/cpu_limit.rs
  rust/psibase/src/services/evaluations.rs
  rust/psibase/src/services/events.rs
  rust/psibase/src/services/fractals.rs
  rust/psibase/src/services/http_server.rs
  rust/psibase/src/services/invite.rs
  rust/psibase/src/services/nft.rs
  rust/psibase/src/services/packages.rs
  rust/psibase/src/services/producers.rs
  rust/psibase/src/services/r_events.rs
  rust/psibase/src/services/setcode.rs
  rust/psibase/src/services/sites.rs
  rust/psibase/src/services/staged_tx.rs
  rust/psibase/src/services/subgroups.rs
  rust/psibase/src/services/symbol.rs
  rust/psibase/src/services/tokens/mod.rs
  rust/psibase/src/services/transact.rs
  rust/psibase/src/services/verify_sig.rs
  rust/psibase/src/time.rs
  rust/psibase/src/web_services.rs
  rust/psibase_macros/psibase-macros-lib/src/service_macro/mod.rs
Labels: Dev Experience

#1359 integrate permissions plugin with package-template
  package-templates/basic-01/{{project-name | upper_camel_case}}/Cargo.toml.liquid
  package-templates/basic-01/{{project-name | upper_camel_case}}/plugin/Cargo.toml.liquid
  package-templates/basic-01/{{project-name | upper_camel_case}}/plugin/src/lib.rs
  package-templates/basic-01/{{project-name | upper_camel_case}}/plugin/wit/impl.wit
  package-templates/basic-01/{{project-name | upper_camel_case}}/plugin/wit/world.wit
Labels: Dev Experience

#1367 add missing authsig permission
  packages/system/AuthSig/plugin/src/lib.rs
Labels: System app

#1364 Add x-transact
  CMakeLists.txt
  libraries/psibase/tester/src/tester.cpp
  packages/local/CMakeLists.txt
  packages/local/XTransact/CMakeLists.txt
  packages/local/XTransact/include/services/local/XTransact.hpp
  packages/local/XTransact/src/XTransact.cpp
  packages/system/Transact/src/RTransact.cpp
Labels: Node infra

#1378 finish moving plugin-ref to host:types
  packages/user/CommonApi/common/packages/component-parser/src/lib.rs
  packages/user/Host/plugin/types/src/lib.rs
  packages/user/Supervisor/ui/src/supervisor.ts
Labels: no-log

#1363 Add packages installation to Config
  packages/Cargo.lock
  packages/system/StagedTx/query-service/src/lib.rs
  packages/user/Config/plugin/Cargo.toml
  packages/user/Config/plugin/src/lib.rs
  packages/user/Config/plugin/wit/impl.wit
  packages/user/Config/plugin/wit/world.wit
  packages/user/Config/ui/src/components/EmptyBlock.tsx
  packages/user/Config/ui/src/components/forms/text-field.tsx
  packages/user/Config/ui/src/components/loading-block.tsx
  packages/user/Config/ui/src/components/nav-main.tsx
  packages/user/Config/ui/src/components/package-item.tsx
  packages/user/Config/ui/src/hooks/use-accept-staged.ts
  packages/user/Config/ui/src/hooks/use-available-packages.ts
  packages/user/Config/ui/src/hooks/use-execute-staged.ts
  packages/user/Config/ui/src/hooks/use-install-packages.ts
  packages/user/Config/ui/src/hooks/use-installed-packages.ts
  packages/user/Config/ui/src/hooks/use-packages.ts
  packages/user/Config/ui/src/hooks/use-plugin-mutation.ts
  packages/user/Config/ui/src/hooks/use-reject-staged.ts
  packages/user/Config/ui/src/hooks/use-remove-staged.ts
  packages/user/Config/ui/src/hooks/use-set-sources.ts
  packages/user/Config/ui/src/hooks/use-sources.ts
  packages/user/Config/ui/src/hooks/use-staged-transaction.ts
  packages/user/Config/ui/src/hooks/use-staged-transactions.ts
  packages/user/Config/ui/src/hooks/use-tx-history.ts
  packages/user/Config/ui/src/lib/checkStaging.ts
  packages/user/Config/ui/src/lib/getActorHistory.ts
  packages/user/Config/ui/src/lib/getSources.ts
  packages/user/Config/ui/src/lib/getStagedByProposer.ts
  packages/user/Config/ui/src/lib/getStagedTx.ts
  packages/user/Config/ui/src/lib/queryKeys.ts
  packages/user/Config/ui/src/lib/semver.ts
  packages/user/Config/ui/src/lib/zod/CommonPackage.ts
  packages/user/Config/ui/src/pages/packages.tsx
  packages/user/Config/ui/src/pages/pending-transaction.tsx
  packages/user/Config/ui/src/pages/pending-transactions.tsx
  packages/user/Config/ui/src/router.tsx
  packages/user/Packages/plugin/src/lib.rs
  packages/user/Packages/plugin/wit/impl.wit
  packages/user/Packages/plugin/wit/world.wit
  rust/psibase/src/services/packages.rs
Labels: System app

#1373 Workaround to avoid always rebuilding evaluations
  packages/user/Evaluations/Cargo.lock
  packages/user/Evaluations/query-service/Cargo.toml
  packages/user/Evaluations/service/Cargo.toml
  packages/user/Fractals/Cargo.lock
Labels: Dev Experience

#1398 Add localstorage manager to supervisor
  packages/user/Supervisor/ui/src/localStorageManager.tsx
  packages/user/Supervisor/ui/src/main.ts
  packages/user/Supervisor/ui/src/mainPage.tsx
Labels: System app

#1397 Supervisor - support embedded mode
  packages/Cargo.lock
  packages/system/Accounts/plugin/accounts/src/helpers.rs
  packages/system/Accounts/plugin/accounts/src/interfaces/api.rs
  packages/system/StagedTx/plugin/src/lib.rs
  packages/user/CommonApi/common/packages/common-lib/src/prompts.ts
  packages/user/Host/plugin/common/src/lib.rs
  packages/user/Host/plugin/common/wit/world.wit
  packages/user/Host/plugin/prompt/Cargo.toml
  packages/user/Host/plugin/prompt/src/db.rs
  packages/user/Host/plugin/prompt/src/errors.rs
  packages/user/Host/plugin/prompt/src/lib.rs
  packages/user/Host/plugin/prompt/wit/deps/supervisor.wit
  packages/user/Host/plugin/prompt/wit/impl.wit
  packages/user/Supervisor/ui/prompt/src/App.tsx
  packages/user/Supervisor/ui/src/component-loading/privileged-api.js
  packages/user/Supervisor/ui/src/hostInterface.ts
  packages/user/Supervisor/ui/src/main.ts
  packages/user/Supervisor/ui/src/plugin/pluginHost.ts
  packages/user/Supervisor/ui/src/supervisor.ts
  packages/user/Supervisor/ui/src/utils.ts
Labels: Dev Experience

#1399 Block deeply-nested permissions requests (by default)
  packages/user/Permissions/plugin/src/db.rs
  packages/user/Permissions/plugin/src/errors.rs
  packages/user/Permissions/plugin/src/lib.rs
  packages/user/Permissions/plugin/wit/world.wit
Labels: Dev Experience

#1382 Fix events after loading a snapshot
  CMakeLists.txt
  doc/src/default-apps/events.md
  libraries/psibase/tester/include/psibase/tester.hpp
  packages/user/Events/CMakeLists.txt
  packages/user/Events/include/services/user/EventIndex.hpp
  packages/user/Events/include/services/user/Events.hpp
  packages/user/Events/include/services/user/EventsTables.hpp
  packages/user/Events/src/EventConfig.cpp
  packages/user/Events/src/EventIndex.cpp
  packages/user/Events/src/REvents.cpp
  packages/user/Events/src/eventKeys.hpp
  packages/user/Events/src/postinstall.json
  packages/user/Events/test/EventsTest.cpp
  packages/user/Invite/src/Invite.cpp
  packages/user/Nft/src/Nft.cpp
  packages/user/Symbol/src/Symbol.cpp
  programs/psitest/main.cpp
  rust/psibase/src/services/events.rs
Labels: Node infra

#1401 Automatically adjust CFT timeout
  libraries/net/include/psibase/auto_timeout.hpp
  libraries/net/include/psibase/cft.hpp
  libraries/net/include/psibase/direct_routing.hpp
  libraries/net/include/psibase/mock_routing.hpp
  libraries/net/include/psibase/shortest_path_routing.hpp
  libraries/net/test/CMakeLists.txt
Labels: Node infra

#1403 Add missing dependency
  CMakeLists.txt
Labels: no-log
