Repository gofractally/psibase, pull requests merged in 2025-06, with the labels that each got.

#1208 Rust SDK - Allow table keys of objects that don't implement the Copy trait
  rust/psibase/src/table.rs
  rust/psibase_macros/psibase-macros-lib/src/service_tables_macro/tables.rs
  services/user/Chainmail/service/src/expanded_table.rs
Labels: Dev Experience, refactoring

#1212 Cleaning up rust sdk for secondary indices
  rust/psibase_macros/psibase-macros-lib/src/service_tables_macro/tables.rs
  services/system/StagedTx/service/src/db.rs
  services/user/Chainmail/service/src/tables.rs
  services/user/Evaluations/service/src/db.rs
  services/user/Registry/service/src/tables.rs
Labels: Dev Experience, refactoring

#948 make http reply only after tx irreversible
  doc/psidk/src/default-apps/transact.md
  libraries/psibase/common/include/psibase/RawNativeFunctions.hpp
  libraries/psibase/common/include/psibase/Service.hpp
  libraries/psibase/common/include/psibase/trace.hpp
  programs/psinode/tests/psinode.py
  programs/psinode/tests/services.py
  rust/psibase/src/main.rs
  rust/psibase/src/native.rs
  rust/psibase/src/rpc.rs
  services/system/Transact/doc/diagrams.md
  services/system/Transact/include/services/system/RTransact.hpp
  services/system/Transact/src/RTransact.cpp
  services/user/XAdmin/ui/src/lib/chainEndpoints.ts
Labels: Node infra

#1220 Fix deprecated usage of pyca/cryptography
  programs/psinode/tests/psinode.py
Labels: no-log

#1219 Move submodule-regression-check.sh into .github/scripts
  .github/scripts/submodule-regression-check.sh
  .github/workflows/submodule-regression.yml
Labels: no-log

#1218 Rename RawNativeFunctions.hpp
  libraries/psibase/common/include/psibase/Actor.hpp
  libraries/psibase/common/include/psibase/Table.hpp
  libraries/psibase/common/include/psibase/api.hpp
  libraries/psibase/common/include/psibase/dispatch.hpp
  libraries/psibase/common/src/KvMerkle.cpp
  libraries/psibase/service/src/intrinsic.cpp
  libraries/psibase/tester/src/chain_polyfill.cpp
  programs/psitest/main.cpp
  services/psibase_tests/test-service.cpp
  services/psibase_tests/test_kv.cpp
  services/system/Accounts/include/services/system/Accounts.hpp
  services/system/CpuLimit/src/CpuLimit.cpp
  services/system/VerifySig/src/VerifySig.cpp
Labels: Dev Experience, refactoring

#1221 add fixed-point ema math
  services/user/Fractals/service/src/scoring.rs
Labels: no-log

#1223 add user-defined resolver to memberships gql query
  services/user/Fractals/service/src/tables.rs
Labels: no-log

#1238 Fix out-dated documentation of log formatter
  doc/psidk/src/run-infrastructure/administration.md
  libraries/psibase/native/src/log.cpp
Labels: documentation, Dev Experience

#1225 Fix building with psidk
  libraries/psibase/CMakeLists.txt
  libraries/psibase/sdk/WASI.cmake
  libraries/psibase/sdk/psibase-config.cmake
  libraries/psibase/sdk/psibase-config.cmake.build
  libraries/psibase/wasm32-psibase/time.h
Labels: bug, Dev Experience

#1246 Move first auth check to RTransact
  CMakeLists.txt
  libraries/psibase/native/include/psibase/BlockContext.hpp
  libraries/psibase/native/include/psibase/ExecutionContext.hpp
  libraries/psibase/native/include/psibase/ForkDb.hpp
  libraries/psibase/native/include/psibase/TransactionContext.hpp
  libraries/psibase/native/src/BlockContext.cpp
  libraries/psibase/native/src/TransactionContext.cpp
  programs/psinode/tests/test_txqueue.py
  programs/psitest/main.cpp
  services/psibase_tests/CMakeLists.txt
  services/psibase_tests/SocketAuth.cpp
  services/psibase_tests/test_socket.cpp
  services/system/Transact/include/services/system/Transact.hpp
  services/system/Transact/src/RTransact.cpp
  services/system/Transact/src/Transact.cpp
  services/system/Transact/test/Transact-test.cpp
Labels: Node infra

#1240 Add wasm service for XAdmin
  CMakeLists.txt
  doc/psidk/src/default-apps/x-admin.md
  doc/psidk/src/doc-root.cpp
  libraries/psibase/common/include/psibase/Rpc.hpp
  libraries/psibase/native/include/psibase/db.hpp
  libraries/psibase/native/src/ExecutionContext.cpp
  libraries/psibase/native/src/NativeFunctions.cpp
  libraries/psibase_http/handle_request.cpp
  programs/psinode/main.cpp
  programs/psinode/tests/services.py
  programs/psinode/tests/test_snapshot.py
  programs/psinode/tests/test_xadmin.py
  rust/gen-cpp-doc/src/main.rs
  rust/psibase/src/services/mod.rs
  rust/psibase/src/services/x_admin.rs
  services/system/Transact/CMakeLists.txt
  services/system/Transact/include/services/system/RTransact.hpp
  services/system/Transact/src/RTransact.cpp
  services/user/CMakeLists.txt
  services/user/XAdmin/CMakeLists.txt
  services/user/XAdmin/include/services/user/XAdmin.hpp
  services/user/XAdmin/query/src/XAdmin.cpp
Labels: System app

#1257 Update minimum supported rust version
  README.md
Labels: documentation, Dev Experience

#1252 Allow setting the number of threads used for the run table
  doc/psidk/src/run-infrastructure/cli/psinode.md
  programs/psinode/config.in
  programs/psinode/main.cpp
Labels: Node infra

#1259 Fix routing p2p messages after a node restarts
  libraries/net/include/psibase/shortest_path_routing.hpp
  programs/psinode/tests/test_crash.py
Labels: bug, Node infra
