Repository gofractally/psibase, pull requests merged in 2025-10, with the labels that each got.

#1425 Mm/extract gen keypair to psibase
  packages/Cargo.lock
  packages/local/XAdmin/ui/src/hooks/useImportAccount.ts
  packages/local/XAdmin/ui/src/lib/bootChain.ts
  packages/local/XAdmin/ui/src/lib/keys.ts
  packages/local/XAdmin/ui/src/pages/create-page.tsx
  packages/local/XAdmin/ui/wasm/Cargo.lock
  packages/local/XAdmin/ui/wasm/src/lib.rs
  packages/local/XAdmin/ui/wasm/wit/world.wit
  packages/system/Accounts/ui/src/hooks/useUnmanagedKeypair.ts
  packages/system/StagedTx/Cargo.lock
  packages/user/Branding/Cargo.lock
  packages/user/BrotliCodec/Cargo.lock
  packages/user/Chainmail/Cargo.lock
  packages/user/Evaluations/Cargo.lock
  packages/user/Fractals/Cargo.lock
  packages/user/Host/plugin/crypto/Cargo.toml
  packages/user/Host/plugin/crypto/src/lib.rs
  packages/user/Identity/Cargo.lock
  packages/user/Profiles/Cargo.lock
  packages/user/Registry/Cargo.lock
  packages/user/Subgroups/Cargo.lock
  packages/user/TokenStream/Cargo.lock
  packages/user/Tokens/Cargo.lock
  rust/Cargo.lock
  rust/psibase/Cargo.toml
  rust/psibase/src/crypto.rs
Labels: Dev Experience, refactoring

#1450 add sites table rust bindings
  rust/psibase/src/schema.rs
  rust/psibase/src/services/sites.rs
Labels: System app

#1467 update token events
  packages/user/Tokens/query-service/src/events.rs
  packages/user/Tokens/service/src/lib.rs
  packages/user/Tokens/service/src/tables.rs
  rust/psibase/src/flags.rs
Labels: no-log

#1465 add sample .clangd file
  .vscode/.clangd
Labels: no-log

#1476 parameterize whether cicd builds run on all platforms
  .github/workflows/on-update.yml
  .github/workflows/ubuntu-builder.yml
Labels: no-log

#1479 Remove leeway option
  programs/psinode/main.cpp
Labels: Node infra, refactoring

#1459 Add db/x-db services and proxy database open through them
  CMakeLists.txt
  libraries/net/test/test_util.cpp
  libraries/psibase/CMakeLists.txt
  libraries/psibase/common/include/psibase/Table.hpp
  libraries/psibase/common/include/psibase/nativeTables.hpp
  libraries/psibase/native/src/NativeFunctions.cpp
  libraries/psibase/service/src/Table.cpp
  libraries/psibase/tester/include/psibase/tester.hpp
  libraries/psibase/tester/src/Table.cpp
  libraries/psibase/tester/src/tester.cpp
  libraries/psio/include/psio/fracpack.hpp
  packages/local/CMakeLists.txt
  packages/local/XAdmin/src/XAdmin.cpp
  packages/local/XDb/CMakeLists.txt
  packages/local/XDb/include/services/local/XDb.hpp
  packages/local/XDb/src/XDb.cpp
  packages/local/XHttp/src/XHttp.cpp
  packages/psibase_tests/include/services/test/TestKV.hpp
  packages/psibase_tests/src/TestServiceEntry.cpp
  packages/psibase_tests/test/test.cpp
  packages/system/CMakeLists.txt
  packages/system/Db/CMakeLists.txt
  packages/system/Db/include/services/system/Db.hpp
  packages/system/Db/src/Db.cpp
  packages/system/Transact/src/Transact.cpp
  packages/user/Events/src/eventKeys.cpp
  packages/user/Events/src/eventKeys.hpp
  programs/psinode/tests/test_subjective.py
  rust/psibase/src/db.rs
  rust/psibase/src/native.rs
  rust/psibase/src/native_raw.rs
  rust/psibase/src/services/db.rs
  rust/psibase/src/services/mod.rs
  rust/psibase/src/services/x_db.rs
  rust/psibase/src/tester.rs
Labels: Dev Experience

#1464 Add candidate producer registration to config app
  packages/Cargo.lock
  packages/system/Producers/include/services/system/Producers.hpp
  packages/system/Producers/plugin/Cargo.toml
  packages/system/Producers/plugin/src/errors.rs
  packages/system/Producers/plugin/src/lib.rs
  packages/system/Producers/plugin/wit/impl.wit
  packages/system/Producers/plugin/wit/world.wit
  packages/system/Producers/src/Producers.cpp
  packages/system/Producers/src/RProducers.cpp
  packages/user/CommonApi/src/CommonApi.cpp
  packages/user/Config/plugin/src/lib.rs
  packages/user/Config/plugin/wit/world.wit
  packages/user/Config/ui/src/hooks/use-candidates.ts
  packages/user/Config/ui/src/lib/producers.ts
  packages/user/Config/ui/src/lib/queryKeys.ts
  packages/user/Config/ui/src/lib/services.ts
  packages/user/Config/ui/src/pages/block-production.tsx
  rust/psibase/src/services/producers.rs
Labels: System app
