Repository gofractally/psibase, pull requests merged in 2025-03, with the labels that each got.

#1086 Handle errors from failure to sign
  libraries/net/include/psibase/bft.hpp
  libraries/net/include/psibase/cft.hpp
  libraries/psibase/native/include/psibase/ForkDb.hpp
  programs/psinode/CMakeLists.txt
  programs/psinode/tests/test_block_signing.py
Labels: bug, Node infra

#1087 Support P-256 keys in the CLI
  rust/Cargo.lock
  rust/psibase/Cargo.toml
  rust/psibase/src/crypto.rs
  services/Cargo.lock
  services/system/StagedTx/Cargo.lock
  services/user/Branding/Cargo.lock
  services/user/Brotli/Cargo.lock
  services/user/Chainmail/Cargo.lock
  services/user/Identity/Cargo.lock
  services/user/Registry/Cargo.lock
  services/user/XAdmin/ui/wasm/Cargo.lock
Labels: Dev Experience

#1091 Add tests for signing transactions with `psibase`
  programs/psinode/tests/name.py
  programs/psinode/tests/psinode.py
  programs/psinode/tests/services.py
  programs/psinode/tests/test_psibase.py
Labels: no-log

#1092 Shorten invite tokens
  .vscode/settings.json.sample
  CMakeLists.txt
  rust/psibase/src/services/invite.rs
  services/Cargo.lock
  services/Cargo.toml
  services/system/Accounts/plugin/account_tokens/Cargo.toml
  services/system/Accounts/plugin/account_tokens/src/lib.rs
  services/system/Accounts/plugin/account_tokens/wit/impl.wit
  services/system/Accounts/plugin/account_tokens/wit/world.wit
  services/system/Accounts/plugin/accounts/Cargo.toml
  services/system/Accounts/ui/src/hooks/useDecodeToken.ts
  services/user/Aes/plugin/Cargo.toml
  services/user/Aes/plugin/src/lib.rs
  services/user/Aes/plugin/wit/impl.wit
  services/user/Aes/plugin/wit/world.wit
  services/user/Base64/plugin/Cargo.toml
  services/user/Base64/plugin/src/lib.rs
  services/user/Base64/plugin/wit/impl.wit
  services/user/Base64/plugin/wit/world.wit
  services/user/CommonApi/common/packages/common-lib/src/rpc.ts
  services/user/CommonApi/common/packages/wit/host-common.wit
  services/user/Fractal/src/Fractal.cpp
  services/user/Homepage/ui/src/pages/Invite.tsx
  services/user/Invite/include/services/user/Invite.hpp
  services/user/Invite/include/services/user/InviteTables.hpp
  services/user/Invite/plugin/Cargo.toml
  services/user/Invite/plugin/src/db.rs
  services/user/Invite/plugin/src/errors.rs
  services/user/Invite/plugin/src/lib.rs
  services/user/Invite/plugin/src/types.rs
  services/user/Invite/plugin/wit/impl.wit
  services/user/Invite/src/Invite.cpp
  services/user/Invite/test/src/Invite-test.cpp
  services/user/Kdf/plugin/Cargo.toml
  services/user/Kdf/plugin/src/lib.rs
  services/user/Kdf/plugin/wit/impl.wit
  services/user/Kdf/plugin/wit/world.wit
  services/user/Registry/plugin/Cargo.toml
  services/user/Supervisor/ui/src/component-loading/host-api.js
  services/user/Supervisor/ui/src/plugin/pluginHost.ts
Labels: System app

#1095 Plugin tester fixes
  services/user/CommonApi/common/packages/plugin-tester/ui/README.md
  services/user/CommonApi/common/packages/plugin-tester/ui/index.html
  services/user/CommonApi/common/packages/plugin-tester/ui/src/PluginLoader.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/ExecutionTabs.tsx
  services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/StringInput.tsx
Labels: bug, System app

#1099 Fix progress indicators
  rust/psibase/src/block.rs
  rust/psibase/src/boot.rs
  rust/psibase/src/lib.rs
  rust/psibase/src/main.rs
  rust/psibase/src/rpc.rs
  rust/psibase/src/tester.rs
  rust/psibase/src/transaction_builder.rs
  services/user/XAdmin/ui/src/components/multi-step-loader.tsx
  services/user/XAdmin/ui/src/lib/bootChain.ts
  services/user/XAdmin/ui/src/pages/create-page.tsx
  services/user/XAdmin/ui/src/types.ts
  services/user/XAdmin/ui/wasm/src/lib.rs
  services/user/XAdmin/ui/wasm/wit/world.wit
Labels: Node infra

#1093 Add query for chain id
  doc/psidk/src/development/front-ends/reference/http-requests.md
  services/system/Transact/plugin/src/lib.rs
  services/user/CommonApi/include/services/system/CommonApi.hpp
  services/user/CommonApi/src/CommonApi.cpp
Labels: System app

#1100 Change brotli package to brotli-codec
  CMakeLists.txt
  programs/psinode/tests/test_psibase.py
  rust/psibase/src/package.rs
  rust/psibase/src/services/brotli_codec.rs
  rust/psibase/src/services/mod.rs
  services/CMakeLists.txt
  services/Cargo.lock
  services/user/Brotli/src/lib.rs
  services/user/BrotliCodec/Cargo.lock
  services/user/BrotliCodec/Cargo.toml
  services/user/BrotliCodec/include/services/user/BrotliCodec.hpp
  services/user/BrotliCodec/plugin/.gitignore
  services/user/BrotliCodec/plugin/Cargo.toml
  services/user/BrotliCodec/plugin/src/errors.rs
  services/user/BrotliCodec/plugin/src/lib.rs
  services/user/BrotliCodec/plugin/wit/impl.wit
  services/user/BrotliCodec/plugin/wit/world.wit
  services/user/BrotliCodec/service/Cargo.toml
  services/user/BrotliCodec/service/src/lib.rs
  services/user/BrotliCodec/src/lib.rs
  services/user/Sites/plugin/Cargo.toml
  services/user/Sites/src/Sites.cpp
Labels: no-log

#1096 Make push_boot an admin API
  doc/psidk/src/development/services/cpp-service/reference/web-services.md
  doc/psidk/src/development/services/rust-service/reference/web-services.md
  doc/psidk/src/run-infrastructure/administration.md
  libraries/psibase_http/handle_request.cpp
  rust/psibase/src/main.rs
  services/user/XAdmin/ui/src/lib/chainEndpoints.ts
Labels: Node infra

#1110 use a newer & better graphiql UI
  rust/psibase/src/serve_http.rs
Labels: Dev Experience

#1109 Package template updates
  package-templates/basic-01/{{project-name | upper_camel_case}}/query-service/src/lib.rs
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/App.tsx
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/use-create-connection-token.ts
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/use-current-accounts.ts
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/use-logged-in-user.ts
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/use-logout.ts
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/use-select-account.ts
  package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/main.tsx
Labels: Dev Experience

#1108 Improve invite app
  CMakeLists.txt
  doc/psidk/src/default-apps/invite.md
  libraries/psibase/common/include/psibase/Table.hpp
  libraries/psibase/common/include/psibase/serveGraphQL.hpp
  libraries/psibase/tester/include/psibase/tester.hpp
  libraries/psio/include/psio/to_hex.hpp
  programs/snapshot/load-snapshot.cpp
  rust/psibase/src/graph_ql.rs
  rust/psibase/src/services/invite.rs
  services/psibase_tests/CMakeLists.txt
  services/psibase_tests/event-service.cpp
  services/psibase_tests/event-service.hpp
  services/psibase_tests/test_event.cpp
  services/system/AuthSig/include/services/system/Spki.hpp
  services/system/AuthSig/src/AuthSig.cpp
  services/system/AuthSig/src/Spki.cpp
  services/user/Fractal/include/services/user/Fractal.hpp
  services/user/Fractal/include/services/user/fractalTables.hpp
  services/user/Fractal/src/Fractal.cpp
  services/user/Fractal/test/src/Fractal-test.cpp
  services/user/Invite/CMakeLists.txt
  services/user/Invite/include/services/user/Invite.hpp
  services/user/Invite/include/services/user/InviteTables.hpp
  services/user/Invite/plugin/src/errors.rs
  services/user/Invite/plugin/src/lib.rs
  services/user/Invite/plugin/src/types.rs
  services/user/Invite/src/Invite.cpp
  services/user/Invite/src/RInvite.cpp
  services/user/Invite/test/src/Invite-test.cpp
  services/user/Nft/include/services/user/nftErrors.hpp
  services/user/Nft/src/Nft.cpp
  services/user/Registry/plugin/src/errors.rs
  services/user/Tokens/plugin/src/errors.rs
  services/user/Tokens/src/Tokens.cpp
  services/user/Tokens/test/src/Tokens-test.cpp
Labels: System app

#1088 Fix compilation with recent boost
  libraries/net/include/psibase/mock_routing.hpp
  libraries/net/include/psibase/mock_timer.hpp
  libraries/net/test/fuzz.hpp
  libraries/net/test/test_consensus.cpp
  libraries/psibase/native/include/psibase/TransactionContext.hpp
  libraries/psibase/native/src/NativeFunctions.cpp
  libraries/psibase_http/http.cpp
Labels: Node infra, refactoring

#1114 Subgroups service
  CMakeLists.txt
  rust/psibase/src/services/mod.rs
  rust/psibase/src/services/subgroups.rs
  rust/psibase/src/tester.rs
  services/user/Invite/plugin/src/db.rs
  services/user/Subgroups/Cargo.lock
  services/user/Subgroups/Cargo.toml
  services/user/Subgroups/README.md
  services/user/Subgroups/service/Cargo.toml
  services/user/Subgroups/service/cpp/include/services/system/Subgroups.hpp
  services/user/Subgroups/service/src/lib.rs
  services/user/Subgroups/service/src/tests.rs
  services/user/Subgroups/src/lib.rs
Labels: System app

#1118 update builder image to the latest
  .github/scripts/build.sh
  .github/workflows/ubuntu-builder.yml
Labels: no-log
